export interface ExerciseStep {
  name: string;
  reps?: string;
  duration?: string;
  description: string;
}

export interface ExerciseTemplate {
  name: string;
  category: 'cardio' | 'strength' | 'flexibility' | 'home';
  caloriesPerMinute: number;
  description: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  steps: ExerciseStep[];
  recommendedMinutes: number;
}

export const exerciseLibrary: ExerciseTemplate[] = [
  {
    name: 'הליכה',
    category: 'cardio',
    caloriesPerMinute: 3.5,
    description: 'הליכה בקצב בינוני - מתאים לכולם',
    difficulty: 'beginner',
    recommendedMinutes: 30,
    steps: [
      { name: 'חימום', duration: '5 דקות', description: 'הליכה איטית להכנת הגוף' },
      { name: 'הליכה בקצב בינוני', duration: '20 דקות', description: 'שמור על קצב קבוע, נשימה חופשית' },
      { name: 'צינון', duration: '5 דקות', description: 'הליכה איטית והורדת דופק' },
    ],
  },
  {
    name: 'הליכה מהירה',
    category: 'cardio',
    caloriesPerMinute: 5.3,
    description: 'הליכה בקצב מהיר עם תנופת ידיים',
    difficulty: 'beginner',
    recommendedMinutes: 30,
    steps: [
      { name: 'חימום', duration: '5 דקות', description: 'הליכה רגילה' },
      { name: 'הליכה מהירה', duration: '20 דקות', description: 'קצב מהיר, תנופת ידיים, צעדים ארוכים' },
      { name: 'צינון', duration: '5 דקות', description: 'הליכה איטית ומתיחות קלות' },
    ],
  },
  {
    name: 'ריצה קלה',
    category: 'cardio',
    caloriesPerMinute: 8.5,
    description: 'ריצה בקצב שאפשר לנהל שיחה',
    difficulty: 'intermediate',
    recommendedMinutes: 25,
    steps: [
      { name: 'חימום - הליכה מהירה', duration: '5 דקות', description: 'הכנת הגוף לריצה' },
      { name: 'ריצה קלה', duration: '15 דקות', description: 'קצב נוח, נשימה סדירה, אפשר לדבר' },
      { name: 'צינון', duration: '5 דקות', description: 'הליכה ומתיחות' },
    ],
  },
  {
    name: 'ריצה',
    category: 'cardio',
    caloriesPerMinute: 15,
    description: 'ריצה בקצב בינוני-מהיר',
    difficulty: 'intermediate',
    recommendedMinutes: 30,
    steps: [
      { name: 'חימום', duration: '5 דקות', description: 'ריצה קלה או הליכה מהירה' },
      { name: 'ריצה בקצב', duration: '20 דקות', description: 'קצב בינוני-מהיר, נשימה מבוקרת' },
      { name: 'צינון', duration: '5 דקות', description: 'ריצה קלה, הליכה ומתיחות' },
    ],
  },
  {
    name: 'ריצה מהירה',
    category: 'cardio',
    caloriesPerMinute: 18,
    description: 'ריצה מהירה מעל 12 קמ"ש - אינטנסיבי',
    difficulty: 'advanced',
    recommendedMinutes: 30,
    steps: [
      { name: 'חימום - ריצה קלה', duration: '5 דקות', description: 'ריצה קלה להכנת השרירים והמפרקים' },
      { name: 'ריצה מהירה', duration: '20 דקות', description: 'קצב מעל 12 קמ"ש, נשימה מהירה אך מבוקרת, שמור על יציבה זקופה' },
      { name: 'צינון', duration: '5 דקות', description: 'ריצה קלה, הליכה ומתיחות רגליים ומותניים' },
    ],
  },
  {
    name: 'ריצת אינטרוולים',
    category: 'cardio',
    caloriesPerMinute: 16,
    description: 'חילופי ריצה מהירה ואיטית - שורף הרבה קלוריות',
    difficulty: 'intermediate',
    recommendedMinutes: 25,
    steps: [
      { name: 'חימום - הליכה מהירה', duration: '3 דקות', description: 'הליכה מהירה להכנת הגוף' },
      { name: 'סט 1: ריצה מהירה', duration: '1 דקה', description: 'ריצה מקסימלית' },
      { name: 'סט 1: ריצה קלה', duration: '2 דקות', description: 'ריצה קלה להתאוששות' },
      { name: 'חזרה על 6 סטים', duration: '18 דקות', description: 'חזור על דקה מהירה + 2 דקות קלות, סה"כ 6 סבבים' },
      { name: 'צינון', duration: '3 דקות', description: 'הליכה ומתיחות' },
    ],
  },
  {
    name: 'רכיבה על אופניים',
    category: 'cardio',
    caloriesPerMinute: 9.5,
    description: 'רכיבה בקצב בינוני',
    difficulty: 'beginner',
    recommendedMinutes: 30,
    steps: [
      { name: 'חימום', duration: '5 דקות', description: 'רכיבה איטית בהילוך קל' },
      { name: 'רכיבה בקצב', duration: '20 דקות', description: 'קצב בינוני, התנגדות בינונית' },
      { name: 'צינון', duration: '5 דקות', description: 'רכיבה איטית' },
    ],
  },
  {
    name: 'שחייה',
    category: 'cardio',
    caloriesPerMinute: 8.5,
    description: 'שחייה חופשית בקצב בינוני',
    difficulty: 'intermediate',
    recommendedMinutes: 30,
    steps: [
      { name: 'חימום', duration: '5 דקות', description: 'שחייה איטית, מתיחות במים' },
      { name: 'שחייה חופשית', duration: '20 דקות', description: 'חתירה סדירה, נשימה כל 3 תנועות' },
      { name: 'צינון', duration: '5 דקות', description: 'שחייה איטית על הגב' },
    ],
  },
  {
    name: 'קפיצה בחבל',
    category: 'cardio',
    caloriesPerMinute: 14,
    description: 'אימון קרדיו אינטנסיבי ויעיל',
    difficulty: 'advanced',
    recommendedMinutes: 15,
    steps: [
      { name: 'חימום', duration: '2 דקות', description: 'קפיצות קלות במקום' },
      { name: 'קפיצה בחבל - סט 1', duration: '1 דקה', description: 'קפיצות רגילות בקצב בינוני' },
      { name: 'מנוחה', duration: '30 שניות', description: 'נשימות עמוקות' },
      { name: 'קפיצה בחבל - סט 2', duration: '1 דקה', description: 'קפיצות מהירות' },
      { name: 'מנוחה', duration: '30 שניות', description: 'נשימות עמוקות' },
      { name: 'קפיצה בחבל - סט 3', duration: '1 דקה', description: 'קפיצות רגל מתחלפת' },
      { name: 'מנוחה', duration: '30 שניות', description: 'נשימות עמוקות' },
      { name: 'חזרה על 3 סטים', duration: '6 דקות', description: 'חזור על הסטים לעיל' },
      { name: 'צינון', duration: '2 דקות', description: 'מתיחות רגליים וידיים' },
    ],
  },
  {
    name: 'סקוואט',
    category: 'strength',
    caloriesPerMinute: 5,
    description: 'כריעות - מחזק רגליים וישבן',
    difficulty: 'beginner',
    recommendedMinutes: 15,
    steps: [
      { name: 'סקוואט רגיל', reps: '15 חזרות × 3 סטים', description: 'רגליים ברוחב כתפיים, ירידה עד 90 מעלות, גב ישר, ברכיים לא עוברות את קצות האצבעות' },
      { name: 'סקוואט רחב (סומו)', reps: '12 חזרות × 3 סטים', description: 'רגליים רחבות, כפות רגליים כלפי חוץ, ירידה עמוקה' },
      { name: 'סקוואט פולס', reps: '20 חזרות × 2 סטים', description: 'ירידה למטה ותנועות קטנות למעלה ולמטה בתחתית' },
      { name: 'סקוואט קפיצה', reps: '10 חזרות × 2 סטים', description: 'סקוואט רגיל עם קפיצה בעלייה - מתקדמים בלבד' },
    ],
  },
  {
    name: 'שכיבות סמיכה',
    category: 'strength',
    caloriesPerMinute: 5,
    description: 'מחזק חזה, כתפיים וזרועות',
    difficulty: 'intermediate',
    recommendedMinutes: 10,
    steps: [
      { name: 'שכיבות סמיכה רגילות', reps: '10 חזרות × 3 סטים', description: 'ידיים ברוחב כתפיים, גוף ישר כמו קרש, ירידה עד שהחזה כמעט נוגע ברצפה' },
      { name: 'שכיבות סמיכה צרות', reps: '8 חזרות × 2 סטים', description: 'ידיים צמודות - מדגיש טרייספס' },
      { name: 'שכיבות סמיכה רחבות', reps: '10 חזרות × 2 סטים', description: 'ידיים רחבות - מדגיש חזה' },
      { name: 'שכיבות על ברכיים (למתחילים)', reps: '12 חזרות × 3 סטים', description: 'אותו תרגיל אבל עם ברכיים על הרצפה - קל יותר' },
    ],
  },
  {
    name: "לאנג'ז",
    category: 'strength',
    caloriesPerMinute: 5,
    description: 'צעדים רחבים - מחזק רגליים',
    difficulty: 'beginner',
    recommendedMinutes: 12,
    steps: [
      { name: "לאנג'ז קדימה", reps: '12 חזרות לכל רגל × 3 סטים', description: 'צעד גדול קדימה, ירידה עד 90 מעלות בשתי הברכיים, גב ישר' },
      { name: "לאנג'ז הליכה", reps: '10 צעדים לכל כיוון × 2 סטים', description: 'כמו לאנג רגיל אבל ממשיכים ללכת קדימה' },
      { name: "לאנג'ז לצד", reps: '10 חזרות לכל צד × 2 סטים', description: 'צעד רחב לצד, כפיפה ברגל המובילה' },
    ],
  },
  {
    name: 'פלאנק',
    category: 'strength',
    caloriesPerMinute: 4,
    description: 'מחזק שרירי ליבה - התחל מ-30 שניות',
    difficulty: 'beginner',
    recommendedMinutes: 8,
    steps: [
      { name: 'פלאנק קדמי', duration: '30-60 שניות × 3 סטים', description: 'על המרפקים וקצות הרגליים, גוף ישר, בטן מכווצת, אל תרים את הישבן' },
      { name: 'פלאנק צידי ימין', duration: '20-30 שניות × 2 סטים', description: 'על מרפק ימין, גוף ישר לצד, ירך למעלה' },
      { name: 'פלאנק צידי שמאל', duration: '20-30 שניות × 2 סטים', description: 'על מרפק שמאל, גוף ישר לצד' },
      { name: 'פלאנק עם הרמת יד', duration: '10 חזרות לכל יד × 2 סטים', description: 'בפלאנק קדמי, מרים יד אחת קדימה לסירוגין' },
    ],
  },
  {
    name: 'בטן',
    category: 'strength',
    caloriesPerMinute: 3,
    description: 'תרגילי בטן - כפיפות ולחיצות',
    difficulty: 'beginner',
    recommendedMinutes: 10,
    steps: [
      { name: 'כפיפות בטן (קראנצ\'ז)', reps: '20 חזרות × 3 סטים', description: 'שכיבה על הגב, ברכיים כפופות, הרמת כתפיים מהרצפה, ידיים מאחורי הראש' },
      { name: 'אופניים באוויר', reps: '15 חזרות לכל צד × 3 סטים', description: 'שכיבה על הגב, תנועת דיווש, מרפק לברך הנגדית' },
      { name: 'הרמת רגליים', reps: '12 חזרות × 3 סטים', description: 'שכיבה על הגב, הרמת רגליים ישרות עד 90 מעלות, הורדה איטית' },
      { name: 'מגע אצבעות לכפות רגליים', reps: '15 חזרות × 2 סטים', description: 'שכיבה עם רגליים למעלה, הושטת ידיים לכיוון כפות הרגליים' },
    ],
  },
  {
    name: 'משקולות - פלג גוף עליון',
    category: 'strength',
    caloriesPerMinute: 6,
    description: 'אימון עם משקולות לידיים וכתפיים',
    difficulty: 'intermediate',
    recommendedMinutes: 25,
    steps: [
      { name: 'כפיפת מרפק (בייספס קרל)', reps: '12 חזרות × 3 סטים', description: 'עמידה, משקולת בכל יד, כפיפת מרפק לכיוון הכתף, הורדה איטית' },
      { name: 'לחיצת כתפיים', reps: '10 חזרות × 3 סטים', description: 'משקולות בגובה כתפיים, דחיפה למעלה, הורדה מבוקרת' },
      { name: 'פרפר עם משקולות', reps: '12 חזרות × 3 סטים', description: 'שכיבה על ספסל/רצפה, ידיים פתוחות לצדדים עם משקולות, הבאה למרכז' },
      { name: 'טרייספס מעל הראש', reps: '10 חזרות × 3 סטים', description: 'משקולת מעל הראש, כפיפת מרפק לאחור, הארכה למעלה' },
      { name: 'חתירה עם משקולת', reps: '10 חזרות לכל יד × 3 סטים', description: 'רגל אחת על ספסל, משיכת משקולת לכיוון הירך' },
    ],
  },
  {
    name: 'משקולות - פלג גוף תחתון',
    category: 'strength',
    caloriesPerMinute: 7.5,
    description: 'סקוואט ומתים עם משקולות',
    difficulty: 'intermediate',
    recommendedMinutes: 25,
    steps: [
      { name: 'סקוואט עם משקולות', reps: '12 חזרות × 3 סטים', description: 'משקולות על הכתפיים או בידיים, ירידה מבוקרת, עלייה פיצוצית' },
      { name: 'מתים רומני', reps: '10 חזרות × 3 סטים', description: 'עמידה, משקולות בידיים, כפיפה מהמותן קדימה, גב ישר, הרגשת מתיחה בירך אחורית' },
      { name: "לאנג'ז עם משקולות", reps: '10 חזרות לכל רגל × 3 סטים', description: 'משקולות בידיים, צעד גדול קדימה וירידה' },
      { name: 'הרמת עקבים', reps: '15 חזרות × 3 סטים', description: 'עמידה על קצות האצבעות עם משקולות, ירידה איטית' },
    ],
  },
  {
    name: 'ברפי',
    category: 'strength',
    caloriesPerMinute: 12.5,
    description: 'תרגיל גוף מלא אינטנסיבי',
    difficulty: 'advanced',
    recommendedMinutes: 10,
    steps: [
      { name: 'ברפי סט 1', reps: '10 חזרות', description: 'עמידה → ירידה לשכיבת סמיכה → שכיבת סמיכה אחת → קפיצה למעלה עם ידיים מעל הראש' },
      { name: 'מנוחה', duration: '30 שניות', description: 'נשימות עמוקות' },
      { name: 'ברפי סט 2', reps: '10 חזרות', description: 'חזרה על אותה תנועה, שמור על טכניקה' },
      { name: 'מנוחה', duration: '30 שניות', description: 'נשימות עמוקות' },
      { name: 'ברפי סט 3', reps: '8 חזרות', description: 'מאמץ אחרון! שמור על טופס' },
    ],
  },
  {
    name: 'יוגה',
    category: 'flexibility',
    caloriesPerMinute: 2.8,
    description: 'משפר גמישות, שיווי משקל ומפחית סטרס',
    difficulty: 'beginner',
    recommendedMinutes: 30,
    steps: [
      { name: 'תנוחת הר (טאדאסנה)', duration: '1 דקה', description: 'עמידה זקופה, רגליים צמודות, ידיים לצדדים, נשימות עמוקות' },
      { name: 'כלב הפוך למטה', duration: '1 דקה', description: 'ידיים ורגליים על הרצפה, ישבן למעלה, גוף בצורת V הפוך' },
      { name: 'לוחם 1 (ויראבהדראסנה)', duration: '30 שניות לכל צד', description: 'רגל אחת קדימה כפופה, רגל אחורית ישרה, ידיים למעלה' },
      { name: 'לוחם 2', duration: '30 שניות לכל צד', description: 'כמו לוחם 1 אבל ידיים לצדדים, מבט קדימה' },
      { name: 'תנוחת עץ', duration: '30 שניות לכל רגל', description: 'עמידה על רגל אחת, כף רגל שנייה על ירך פנימית, ידיים למעלה' },
      { name: 'תנוחת ילד', duration: '1 דקה', description: 'כריעה, ישבן על עקבים, ידיים מושטות קדימה, מצח על הרצפה' },
      { name: 'שאווסנה (מנוחה)', duration: '3 דקות', description: 'שכיבה על הגב, עיניים עצומות, נשימות עמוקות' },
    ],
  },
  {
    name: 'פילאטיס',
    category: 'flexibility',
    caloriesPerMinute: 3.5,
    description: 'מחזק שרירי ליבה ומשפר יציבה',
    difficulty: 'intermediate',
    recommendedMinutes: 25,
    steps: [
      { name: 'מאה (The Hundred)', reps: '100 תנועות (10 סטים × 10)', description: 'שכיבה, רגליים באלכסון, ידיים לצדדים, תנועות קצרות למעלה ולמטה' },
      { name: 'גלגול למעלה (Roll Up)', reps: '8 חזרות', description: 'שכיבה, עלייה איטית לישיבה עם ידיים מושטות, גלגול חזרה' },
      { name: 'מעגלי רגל', reps: '8 מעגלים לכל כיוון, לכל רגל', description: 'שכיבה, רגל אחת למעלה, מעגלים בכיוון השעון ונגדו' },
      { name: 'גשר (Bridge)', reps: '10 חזרות × 3 סטים', description: 'שכיבה, ברכיים כפופות, הרמת אגן, החזקה 3 שניות' },
    ],
  },
  {
    name: 'מתיחות',
    category: 'flexibility',
    caloriesPerMinute: 1.8,
    description: 'מתיחות לכל הגוף - חשוב אחרי אימון',
    difficulty: 'beginner',
    recommendedMinutes: 15,
    steps: [
      { name: 'מתיחת צוואר', duration: '30 שניות לכל צד', description: 'הטיית ראש לצד, החזקה עדינה עם יד' },
      { name: 'מתיחת כתפיים', duration: '30 שניות לכל יד', description: 'יד אחת לרוחב הגוף, החזקה עם יד שנייה' },
      { name: 'מתיחת חזה', duration: '30 שניות', description: 'ידיים מאחורי הגב, שלובות, הרמה למעלה' },
      { name: 'מתיחת ירך אחורית', duration: '30 שניות לכל רגל', description: 'ישיבה, רגל ישרה, הושטה לכיוון כף הרגל' },
      { name: 'מתיחת ירך קדמית', duration: '30 שניות לכל רגל', description: 'עמידה, כפיפת רגל לאחור, החזקת כף הרגל' },
      { name: 'מתיחת גב תחתון', duration: '30 שניות', description: 'שכיבה, ברכיים לחזה, חיבוק עדין' },
    ],
  },
  {
    name: 'אימון HIIT ביתי',
    category: 'home',
    caloriesPerMinute: 12,
    description: '20 דקות של מאמץ גבוה עם הפסקות קצרות',
    difficulty: 'advanced',
    recommendedMinutes: 20,
    steps: [
      { name: 'חימום - ריצה במקום', duration: '2 דקות', description: 'ריצה קלה במקום, הרמת ברכיים' },
      { name: 'סקוואט קפיצה', duration: '40 שניות עבודה, 20 שניות מנוחה', description: 'סקוואט + קפיצה למעלה, נחיתה רכה' },
      { name: 'שכיבות סמיכה', duration: '40 שניות עבודה, 20 שניות מנוחה', description: 'שכיבות סמיכה בקצב' },
      { name: 'הרמת ברכיים גבוה', duration: '40 שניות עבודה, 20 שניות מנוחה', description: 'ריצה במקום עם ברכיים גבוהות' },
      { name: 'ברפי', duration: '40 שניות עבודה, 20 שניות מנוחה', description: 'ברפי מלא בקצב' },
      { name: 'פלאנק דינמי', duration: '40 שניות עבודה, 20 שניות מנוחה', description: 'פלאנק עם תנועה - מרפקים לידיים ישרות' },
      { name: 'חזרה על כל הסבב', duration: '8 דקות', description: 'חזור על כל 5 התרגילים פעם נוספת' },
      { name: 'צינון ומתיחות', duration: '2 דקות', description: 'מתיחות קלות לכל הגוף' },
    ],
  },
  {
    name: 'אימון טאבטה',
    category: 'home',
    caloriesPerMinute: 13,
    description: '4 דקות: 20 שניות מאמץ, 10 שניות מנוחה × 8 סבבים',
    difficulty: 'advanced',
    recommendedMinutes: 16,
    steps: [
      { name: 'חימום', duration: '2 דקות', description: 'ריצה קלה במקום ומתיחות דינמיות' },
      { name: 'טאבטה 1: סקוואט', duration: '4 דקות (8×20/10)', description: '20 שניות סקוואט מקסימלי, 10 שניות מנוחה, 8 פעמים' },
      { name: 'מנוחה', duration: '1 דקה', description: 'נשימות, שתייה' },
      { name: 'טאבטה 2: שכיבות סמיכה', duration: '4 דקות (8×20/10)', description: '20 שניות שכיבות מקסימלי, 10 שניות מנוחה, 8 פעמים' },
      { name: 'מנוחה', duration: '1 דקה', description: 'נשימות, שתייה' },
      { name: 'טאבטה 3: ברפי', duration: '4 דקות (8×20/10)', description: '20 שניות ברפי מקסימלי, 10 שניות מנוחה, 8 פעמים' },
    ],
  },
  {
    name: 'ריקוד',
    category: 'home',
    caloriesPerMinute: 8,
    description: 'ריקוד חופשי או עם סרטון - כיף ושריפת קלוריות',
    difficulty: 'beginner',
    recommendedMinutes: 30,
    steps: [
      { name: 'חימום', duration: '5 דקות', description: 'תנועות קלות, מתיחות דינמיות' },
      { name: 'ריקוד חופשי', duration: '20 דקות', description: 'תן למוזיקה להוביל! שים שיר אהוב וזוז' },
      { name: 'צינון', duration: '5 דקות', description: 'ריקוד איטי ומתיחות' },
    ],
  },
  {
    name: 'עליית מדרגות',
    category: 'home',
    caloriesPerMinute: 13,
    description: 'עלייה וירידה במדרגות - אימון קרדיו מצוין',
    difficulty: 'beginner',
    recommendedMinutes: 15,
    steps: [
      { name: 'עלייה וירידה רגילה', duration: '5 דקות', description: 'עלייה וירידה בקצב נוח' },
      { name: 'עלייה מהירה', duration: '3 דקות', description: 'עלייה בקצב מהיר, ירידה בקצב רגיל' },
      { name: 'עלייה עם דילוג מדרגה', duration: '3 דקות', description: 'עלייה בדילוג על מדרגה (מתקדמים)' },
      { name: 'צינון', duration: '4 דקות', description: 'עלייה וירידה איטית, מתיחות' },
    ],
  },
  {
    name: 'משקולות 5 ק"ג - זרועות',
    category: 'strength',
    caloriesPerMinute: 5.5,
    description: 'אימון זרועות וכתפיים עם משקולות 5 ק"ג בבית',
    difficulty: 'beginner',
    recommendedMinutes: 20,
    steps: [
      { name: 'חימום - סיבובי כתפיים', duration: '2 דקות', description: 'סיבובים קדימה ואחורה, ללא משקולות' },
      { name: 'בייספס קרל', reps: '12 חזרות × 3 סטים', description: 'עמידה, משקולת 5 ק"ג בכל יד, כפיפת מרפק לכיוון הכתף, הורדה איטית' },
      { name: 'לחיצת כתפיים', reps: '10 חזרות × 3 סטים', description: 'משקולות בגובה אוזניים, דחיפה ישרה למעלה, הורדה מבוקרת' },
      { name: 'הרמה צידית', reps: '12 חזרות × 3 סטים', description: 'ידיים לצדדים, הרמה עד גובה כתפיים, מרפקים מעט כפופים' },
      { name: 'טרייספס מעל הראש', reps: '10 חזרות × 3 סטים', description: 'משקולת אחת בשתי ידיים מעל הראש, כפיפה לאחור, הארכה למעלה' },
      { name: 'פטיש קרל', reps: '12 חזרות × 3 סטים', description: 'כמו בייספס אבל כפות הידיים פונות פנימה - מחזק את האמה' },
      { name: 'מתיחות זרועות', duration: '2 דקות', description: 'מתיחת בייספס, טרייספס וכתפיים' },
    ],
  },
  {
    name: 'משקולות 5 ק"ג - חזה וגב',
    category: 'strength',
    caloriesPerMinute: 6,
    description: 'חיזוק חזה וגב עם משקולות 5 ק"ג',
    difficulty: 'beginner',
    recommendedMinutes: 20,
    steps: [
      { name: 'חימום', duration: '2 דקות', description: 'סיבובי זרועות ומתיחות דינמיות' },
      { name: 'לחיצת חזה שכיבה', reps: '12 חזרות × 3 סטים', description: 'שכיבה על הגב (ספסל/רצפה), משקולת בכל יד, דחיפה למעלה ישר, הורדה איטית' },
      { name: 'פרפר (פלייז)', reps: '10 חזרות × 3 סטים', description: 'שכיבה, ידיים פתוחות לצדדים עם משקולות, הבאה למרכז כמו חיבוק' },
      { name: 'חתירה בכפיפה', reps: '12 חזרות × 3 סטים', description: 'כפיפה קדימה 45°, משיכת משקולות לכיוון הבטן, לחיצת שכמות' },
      { name: 'חתירה ביד אחת', reps: '10 חזרות לכל יד × 3 סטים', description: 'יד אחת על כיסא, משיכת משקולת לכיוון הירך, החלפה' },
      { name: 'פול-אובר', reps: '10 חזרות × 3 סטים', description: 'שכיבה, משקולת בשתי ידיים מעל החזה, הורדה מאחורי הראש, חזרה' },
      { name: 'מתיחות', duration: '2 דקות', description: 'מתיחת חזה, גב ושכמות' },
    ],
  },
  {
    name: 'משקולות 5 ק"ג - רגליים וישבן',
    category: 'strength',
    caloriesPerMinute: 7,
    description: 'חיזוק פלג גוף תחתון עם משקולות 5 ק"ג',
    difficulty: 'beginner',
    recommendedMinutes: 20,
    steps: [
      { name: 'חימום - סקוואט ללא משקל', duration: '2 דקות', description: 'סקוואט גוף ומתיחות דינמיות' },
      { name: 'סקוואט גוביילט', reps: '15 חזרות × 3 סטים', description: 'החזקת משקולת אחת בשתי ידיים מול החזה, סקוואט עמוק' },
      { name: 'לאנג\'ז עם משקולות', reps: '12 חזרות לכל רגל × 3 סטים', description: 'משקולת בכל יד, צעד גדול קדימה וירידה, ברכיים 90 מעלות' },
      { name: 'מתים רומני', reps: '12 חזרות × 3 סטים', description: 'משקולות בידיים, כפיפה מהמותן קדימה, גב ישר, הרגשת מתיחה בירך אחורית' },
      { name: 'הרמת אגן (גלוט ברידג\')', reps: '15 חזרות × 3 סטים', description: 'שכיבה, משקולת על האגן, הרמה ולחיצת ישבן למעלה' },
      { name: 'הרמת עקבים', reps: '20 חזרות × 3 סטים', description: 'עמידה עם משקולות, עלייה על קצות האצבעות, ירידה איטית' },
      { name: 'מתיחות רגליים', duration: '2 דקות', description: 'מתיחת ירך קדמית, אחורית ותאומים' },
    ],
  },
  {
    name: 'משקולות 5 ק"ג - גוף מלא',
    category: 'strength',
    caloriesPerMinute: 7,
    description: 'אימון כל הגוף עם משקולות 5 ק"ג - סבב אחד שלם',
    difficulty: 'intermediate',
    recommendedMinutes: 30,
    steps: [
      { name: 'חימום', duration: '3 דקות', description: 'ריצה במקום, סיבובי ידיים, סקוואט גוף' },
      { name: 'סקוואט + לחיצת כתפיים', reps: '10 חזרות × 3 סטים', description: 'סקוואט עם משקולות ובעלייה דחיפה למעלה - תרגיל משולב מעולה' },
      { name: 'חתירה בכפיפה', reps: '12 חזרות × 3 סטים', description: 'כפיפה 45°, משיכת משקולות לבטן' },
      { name: 'לאנג\'ז + בייספס קרל', reps: '10 חזרות לכל רגל × 2 סטים', description: 'לאנג\' קדימה ובמקביל כפיפת מרפק' },
      { name: 'לחיצת חזה שכיבה', reps: '12 חזרות × 3 סטים', description: 'שכיבה על הגב, לחיצה למעלה' },
      { name: 'מתים רומני', reps: '10 חזרות × 3 סטים', description: 'כפיפה מהמותן, גב ישר' },
      { name: 'פלאנק עם חתירה', reps: '8 חזרות לכל יד × 2 סטים', description: 'פלאנק על משקולות, משיכת יד אחת לצד בזמן שמירה על יציבות' },
      { name: 'מתיחות', duration: '3 דקות', description: 'מתיחות לכל הגוף' },
    ],
  },
  {
    name: 'הליכה על הליכון',
    category: 'cardio',
    caloriesPerMinute: 5,
    description: 'הליכה על מסילה חשמלית - שליטה מלאה בקצב ושיפוע',
    difficulty: 'beginner',
    recommendedMinutes: 30,
    steps: [
      { name: 'חימום - קצב 4 קמ"ש', duration: '5 דקות', description: 'הליכה איטית להכנת הגוף' },
      { name: 'הליכה בקצב 5-6 קמ"ש', duration: '20 דקות', description: 'קצב בינוני, אפשר להעלות שיפוע ל-3-5%' },
      { name: 'צינון', duration: '5 דקות', description: 'הורדת מהירות ל-3-4 קמ"ש' },
    ],
  },
  {
    name: 'אליפטיקל',
    category: 'cardio',
    caloriesPerMinute: 8,
    description: 'מכשיר קרדיו עדין על המפרקים - עובד על כל הגוף',
    difficulty: 'beginner',
    recommendedMinutes: 25,
    steps: [
      { name: 'חימום', duration: '3 דקות', description: 'קצב נמוך, התנגדות נמוכה' },
      { name: 'אימון בקצב בינוני', duration: '10 דקות', description: 'קצב בינוני, התנגדות 5-7' },
      { name: 'אינטרוולים', duration: '8 דקות', description: 'דקה התנגדות גבוהה + דקה נמוכה' },
      { name: 'צינון', duration: '4 דקות', description: 'קצב איטי, התנגדות נמוכה' },
    ],
  },
  {
    name: 'אגרוף / קיקבוקסינג',
    category: 'cardio',
    caloriesPerMinute: 10,
    description: 'אימון אגרוף ובעיטות - קרדיו אינטנסיבי ושחרור מתח',
    difficulty: 'intermediate',
    recommendedMinutes: 25,
    steps: [
      { name: 'חימום - ריצה במקום', duration: '3 דקות', description: 'ריצה קלה וסיבובי כתפיים' },
      { name: 'אגרופים ישרים', duration: '2 דקות', description: 'ג\'אב וקרוס - אגרוף ימין ושמאל לסירוגין' },
      { name: 'אפרקטים', duration: '2 דקות', description: 'אגרופים מלמטה למעלה' },
      { name: 'הוקים', duration: '2 דקות', description: 'אגרופים מהצד' },
      { name: 'בעיטות קדמיות', duration: '2 דקות', description: 'בעיטה ישרה קדימה, חלופי רגליים' },
      { name: 'בעיטות צדדיות', duration: '2 דקות', description: 'בעיטה לצד, חלופי רגליים' },
      { name: 'קומבינציות', duration: '8 דקות', description: 'שילוב אגרופים ובעיטות ברצף' },
      { name: 'צינון ומתיחות', duration: '4 דקות', description: 'מתיחות רגליים וידיים' },
    ],
  },
  {
    name: 'סט בטן מתקדם',
    category: 'strength',
    caloriesPerMinute: 5,
    description: 'תרגילי בטן מגוונים לחיזוק כל שרירי הליבה',
    difficulty: 'intermediate',
    recommendedMinutes: 15,
    steps: [
      { name: 'פלאנק קדמי', duration: '45 שניות', description: 'על המרפקים, גוף ישר כמו קרש' },
      { name: 'פלאנק צידי ימין', duration: '30 שניות', description: 'על מרפק ימין, ירך למעלה' },
      { name: 'פלאנק צידי שמאל', duration: '30 שניות', description: 'על מרפק שמאל' },
      { name: 'אופניים באוויר', reps: '20 חזרות לכל צד', description: 'מרפק לברך הנגדית' },
      { name: 'הרמת רגליים', reps: '15 חזרות', description: 'שכיבה, הרמת רגליים ישרות ל-90 מעלות' },
      { name: 'V-ups', reps: '12 חזרות', description: 'הרמת רגליים וגוף בו-זמנית ליצירת V' },
      { name: 'מגב רוסי', reps: '20 חזרות', description: 'ישיבה, סיבוב פלג גוף עליון מצד לצד' },
      { name: 'mountain climbers', duration: '30 שניות', description: 'פלאנק עם ריצת ברכיים קדימה' },
      { name: 'חזרה על הסבב', duration: '5 דקות', description: 'חזור על כל התרגילים פעם נוספת' },
    ],
  },
  {
    name: 'אימון גומיות',
    category: 'home',
    caloriesPerMinute: 5,
    description: 'אימון כוח עם גומיות התנגדות - קל לאחסון ויעיל',
    difficulty: 'beginner',
    recommendedMinutes: 20,
    steps: [
      { name: 'חימום', duration: '2 דקות', description: 'סיבובי ידיים ומתיחות דינמיות' },
      { name: 'משיכה רחבה', reps: '12 חזרות × 3 סטים', description: 'גומיה מעל הראש, משיכה לצדדים למטה' },
      { name: 'לחיצת חזה', reps: '12 חזרות × 3 סטים', description: 'גומיה מאחורי הגב, דחיפה קדימה' },
      { name: 'בייספס קרל', reps: '12 חזרות × 3 סטים', description: 'עמידה על הגומיה, כפיפת מרפק' },
      { name: 'סקוואט עם גומיה', reps: '15 חזרות × 3 סטים', description: 'גומיה מעל הברכיים, סקוואט עם דחיפה החוצה' },
      { name: 'הליכה צידית', reps: '10 צעדים לכל צד × 3 סטים', description: 'גומיה על הקרסוליים, צעידה לצד' },
      { name: 'מתיחות', duration: '2 דקות', description: 'מתיחות לכל הגוף' },
    ],
  },
  {
    name: 'TRX / רצועות',
    category: 'strength',
    caloriesPerMinute: 7,
    description: 'אימון תלייה עם רצועות - מחזק ליבה ויציבות',
    difficulty: 'intermediate',
    recommendedMinutes: 25,
    steps: [
      { name: 'חימום', duration: '3 דקות', description: 'מתיחות דינמיות וסיבובים' },
      { name: 'חתירה (TRX Row)', reps: '12 חזרות × 3 סטים', description: 'אחיזה ברצועות, גוף באלכסון, משיכה לחזה' },
      { name: 'לחיצת חזה', reps: '10 חזרות × 3 סטים', description: 'פנים לרצפה, דחיפה מהרצועות' },
      { name: 'סקוואט TRX', reps: '15 חזרות × 3 סטים', description: 'אחיזה ברצועות, סקוואט עמוק עם שיווי משקל' },
      { name: 'פלאנק עם רגליים ברצועות', duration: '30 שניות × 3 סטים', description: 'רגליים ברצועות, פלאנק מאתגר' },
      { name: 'לאנג\'ז + רצועות', reps: '10 חזרות לכל רגל × 2 סטים', description: 'רגל אחורית ברצועה, לאנג\' מאתגר' },
      { name: 'מתיחות', duration: '3 דקות', description: 'מתיחות עם הרצועות' },
    ],
  },
  {
    name: 'הליכה נורדית',
    category: 'cardio',
    caloriesPerMinute: 7,
    description: 'הליכה עם מקלות - שורף 40% יותר קלוריות מהליכה רגילה',
    difficulty: 'beginner',
    recommendedMinutes: 30,
    steps: [
      { name: 'חימום - הליכה רגילה', duration: '5 דקות', description: 'הליכה איטית עם המקלות לצד' },
      { name: 'הליכה נורדית', duration: '20 דקות', description: 'תנופת מקלות מתואמת - מקל ימני עם רגל שמאלית. גב ישר, מבט קדימה' },
      { name: 'צינון', duration: '5 דקות', description: 'הליכה איטית ומתיחות עם המקלות' },
    ],
  },
  {
    name: 'דיפס (שקיעות)',
    category: 'strength',
    caloriesPerMinute: 6,
    description: 'חיזוק טרייספס וחזה על כיסא או ספסל',
    difficulty: 'intermediate',
    recommendedMinutes: 12,
    steps: [
      { name: 'חימום כתפיים', duration: '2 דקות', description: 'סיבובי כתפיים ומתיחות דינמיות' },
      { name: 'דיפס על כיסא', reps: '10 חזרות × 3 סטים', description: 'ידיים על קצה כיסא, ירידה עד 90° במרפקים, דחיפה למעלה' },
      { name: 'דיפס עם רגליים ישרות', reps: '8 חזרות × 3 סטים', description: 'רגליים ישרות - יותר קשה. מרפקים צמודים לגוף' },
      { name: 'דיפס עם החזקה', reps: '6 חזרות × 2 סטים', description: 'ירידה + החזקה 3 שניות למטה + עלייה' },
      { name: 'מתיחות', duration: '2 דקות', description: 'מתיחת טרייספס וכתפיים' },
    ],
  },
  {
    name: 'סופרמן (גב)',
    category: 'strength',
    caloriesPerMinute: 3.5,
    description: 'חיזוק שרירי גב תחתון ועליון',
    difficulty: 'beginner',
    recommendedMinutes: 10,
    steps: [
      { name: 'סופרמן קלאסי', reps: '10 חזרות × 3 סטים', description: 'שכיבה על הבטן, הרמת ידיים ורגליים בו-זמנית, החזקה 3 שניות' },
      { name: 'סופרמן חלופי', reps: '12 חזרות לכל צד × 3 סטים', description: 'הרמת יד ימין + רגל שמאל, ולהיפך' },
      { name: 'שחיין', reps: '20 תנועות × 3 סטים', description: 'כמו סופרמן אבל עם תנועת שחייה - ידיים ורגליים מתחלפות' },
      { name: 'Y-raise', reps: '10 חזרות × 3 סטים', description: 'הרמת ידיים בצורת Y, לחיצת שכמות' },
    ],
  },
  {
    name: 'צמד כתפיים',
    category: 'strength',
    caloriesPerMinute: 5,
    description: 'אימון כתפיים מקיף ללא ציוד או עם משקולות קלות',
    difficulty: 'beginner',
    recommendedMinutes: 12,
    steps: [
      { name: 'חימום - סיבובי כתפיים', duration: '1 דקה', description: 'סיבובים קדימה ואחורה' },
      { name: 'לחיצת כתפיים (Pike Push-up)', reps: '8 חזרות × 3 סטים', description: 'שכיבת סמיכה עם ישבן למעלה, דחיפה אנכית' },
      { name: 'הרמה צידית', reps: '12 חזרות × 3 סטים', description: 'ידיים לצדדים עד גובה כתפיים. עם או בלי משקולות' },
      { name: 'הרמה קדמית', reps: '10 חזרות × 3 סטים', description: 'הרמת ידיים קדימה עד גובה כתפיים' },
      { name: 'פרפר הפוך (Reverse Fly)', reps: '12 חזרות × 3 סטים', description: 'כפיפה קדימה, הרמת ידיים לצדדים - כתף אחורית' },
      { name: 'שראגס', reps: '15 חזרות × 3 סטים', description: 'הרמת כתפיים למעלה לכיוון האוזניים' },
      { name: 'מתיחות כתפיים', duration: '2 דקות', description: 'מתיחת כתפיים מכל הזוויות' },
    ],
  },
  {
    name: 'אימון חזה ביתי',
    category: 'strength',
    caloriesPerMinute: 6,
    description: 'חיזוק שרירי חזה בבית ללא ציוד',
    difficulty: 'intermediate',
    recommendedMinutes: 15,
    steps: [
      { name: 'חימום', duration: '2 דקות', description: 'סיבובי ידיים ומתיחות דינמיות' },
      { name: 'שכיבות סמיכה רגילות', reps: '10 חזרות × 3 סטים', description: 'ידיים ברוחב כתפיים, ירידה מבוקרת' },
      { name: 'שכיבות סמיכה רחבות', reps: '10 חזרות × 3 סטים', description: 'ידיים רחבות - מדגיש חזה חיצוני' },
      { name: 'שכיבות סמיכה צרות (יהלום)', reps: '8 חזרות × 3 סטים', description: 'ידיים יוצרות צורת יהלום - טרייספס + חזה פנימי' },
      { name: 'שכיבות עם רגליים מוגבהות', reps: '8 חזרות × 3 סטים', description: 'רגליים על כיסא - מדגיש חזה עליון' },
      { name: 'פלאנק ללחיצה', reps: '8 חזרות × 2 סטים', description: 'מפלאנק על מרפקים → דחיפה לידיים ישרות → חזרה' },
      { name: 'מתיחות חזה', duration: '2 דקות', description: 'מתיחת חזה בפתח דלת, מתיחת כתפיים' },
    ],
  },
  {
    name: 'אימון גב ביתי',
    category: 'strength',
    caloriesPerMinute: 5,
    description: 'חיזוק שרירי גב ללא ציוד',
    difficulty: 'beginner',
    recommendedMinutes: 12,
    steps: [
      { name: 'חימום', duration: '2 דקות', description: 'סיבובי גוף ומתיחות' },
      { name: 'סופרמן', reps: '10 חזרות × 3 סטים', description: 'שכיבה על הבטן, הרמת ידיים ורגליים' },
      { name: 'חתירה הפוכה (שולחן)', reps: '10 חזרות × 3 סטים', description: 'שכיבה מתחת לשולחן, משיכה למעלה' },
      { name: 'Bird Dog', reps: '10 חזרות לכל צד × 3 סטים', description: 'על ארבע, הרמת יד + רגל נגדית' },
      { name: 'גשר (Bridge)', reps: '15 חזרות × 3 סטים', description: 'שכיבה, הרמת אגן, לחיצת ישבן' },
      { name: 'מתיחות גב', duration: '2 דקות', description: 'תנוחת ילד, סיבובי גב, חתול-פרה' },
    ],
  },
  {
    name: 'אימון זרועות ללא ציוד',
    category: 'strength',
    caloriesPerMinute: 4.5,
    description: 'חיזוק בייספס וטרייספס בבית ללא משקולות',
    difficulty: 'beginner',
    recommendedMinutes: 12,
    steps: [
      { name: 'חימום', duration: '2 דקות', description: 'סיבובי פרקי כף היד וזרועות' },
      { name: 'דיפס על כיסא', reps: '10 חזרות × 3 סטים', description: 'טרייספס - ירידה ועלייה על כיסא' },
      { name: 'שכיבות סמיכה צרות', reps: '8 חזרות × 3 סטים', description: 'טרייספס - ידיים צמודות' },
      { name: 'בייספס איזומטרי', duration: '30 שניות × 3 סטים', description: 'לחיצת כפות ידיים זו בזו בכפיפה - מתח סטטי' },
      { name: 'Chin-up שלילי', reps: '5 חזרות × 3 סטים', description: 'אם יש מוט - קפיצה למעלה וירידה איטית (5 שניות)' },
      { name: 'הליכת דוב', duration: '1 דקה × 2 סטים', description: 'הליכה על ארבע - ידיים ורגליים, עובד על כל הזרועות' },
      { name: 'מתיחות', duration: '2 דקות', description: 'מתיחת בייספס וטרייספס' },
    ],
  },
  {
    name: 'קטלבל / כדור משקל',
    category: 'strength',
    caloriesPerMinute: 10,
    description: 'אימון עם כדור משקל - כוח וקרדיו ביחד',
    difficulty: 'intermediate',
    recommendedMinutes: 20,
    steps: [
      { name: 'חימום', duration: '3 דקות', description: 'סיבובים, סקוואט גוף, מתיחות' },
      { name: 'סווינג (נדנוד)', reps: '15 חזרות × 4 סטים', description: 'אחיזה בשתי ידיים, נדנוד בין הרגליים עד גובה כתפיים. כוח מהירכיים!' },
      { name: 'גוביילט סקוואט', reps: '12 חזרות × 3 סטים', description: 'החזקת הכדור מול החזה, סקוואט עמוק' },
      { name: 'לחיצה חד-צדדית', reps: '8 חזרות לכל יד × 3 סטים', description: 'לחיצה מהכתף למעלה ביד אחת' },
      { name: 'חתירה חד-צדדית', reps: '10 חזרות לכל יד × 3 סטים', description: 'כפיפה, משיכת כדור לירך' },
      { name: 'Turkish Get-up', reps: '3 חזרות לכל צד × 2 סטים', description: 'שכיבה עם כדור ביד → עמידה מלאה → חזרה. תרגיל מלך!' },
      { name: 'מתיחות', duration: '3 דקות', description: 'מתיחות לכל הגוף' },
    ],
  },
  {
    name: 'מתח (Pull-ups)',
    category: 'strength',
    caloriesPerMinute: 8,
    description: 'מתח וצ\'ין-אפ - מלך תרגילי הגב והזרועות',
    difficulty: 'advanced',
    recommendedMinutes: 15,
    steps: [
      { name: 'חימום', duration: '2 דקות', description: 'תליה חופשית, סיבובי כתפיים' },
      { name: 'מתח רחב (Pull-up)', reps: '5-8 חזרות × 4 סטים', description: 'אחיזה רחבה, משיכה עד שהסנטר מעל המוט. גב!' },
      { name: 'צ\'ין-אפ (Chin-up)', reps: '5-8 חזרות × 3 סטים', description: 'אחיזה צרה הפוכה - בייספס + גב' },
      { name: 'מתח שלילי', reps: '5 חזרות × 3 סטים', description: 'קפיצה למעלה, ירידה איטית 5 שניות - למי שלא מצליח מתח מלא' },
      { name: 'תליה פעילה', duration: '20 שניות × 3 סטים', description: 'תליה עם כתפיים נמוכות (שכמות מכווצות) - בונה כוח אחיזה' },
      { name: 'מתיחות', duration: '2 דקות', description: 'מתיחת גב, כתפיים ובייספס' },
    ],
  },
];

export const categoryLabels: Record<string, string> = {
  cardio: 'קרדיו',
  strength: 'כוח',
  flexibility: 'גמישות',
  home: 'אימון ביתי',
};

export const difficultyLabels: Record<string, string> = {
  beginner: 'מתחיל',
  intermediate: 'בינוני',
  advanced: 'מתקדם',
};
