export interface FoodItem {
  name: string;
  calories: number;
  protein: number;
  fat: number;
  carbs: number;
  portion: string;
  category: string;
  emoji: string;
}

export const foodDatabase: FoodItem[] = [
  // לחמים ופחמימות
  { name: 'פרוסת לחם לבן', calories: 80, protein: 3, fat: 1, carbs: 15, portion: 'פרוסה', category: 'לחמים', emoji: '🍞' },
  { name: 'פרוסת לחם מלא', calories: 70, protein: 3, fat: 1, carbs: 12, portion: 'פרוסה', category: 'לחמים', emoji: '🍞' },
  { name: 'פיתה', calories: 165, protein: 5, fat: 1, carbs: 33, portion: 'יחידה', category: 'לחמים', emoji: '🫓' },
  { name: 'פיתה מלאה', calories: 150, protein: 6, fat: 1, carbs: 28, portion: 'יחידה', category: 'לחמים', emoji: '🫓' },
  { name: 'לחמנייה', calories: 150, protein: 5, fat: 2, carbs: 28, portion: 'יחידה', category: 'לחמים', emoji: '🥖' },
  { name: 'באגט', calories: 140, protein: 4, fat: 1, carbs: 28, portion: 'פרוסה', category: 'לחמים', emoji: '🥖' },
  { name: 'לאפה', calories: 200, protein: 6, fat: 2, carbs: 38, portion: 'יחידה', category: 'לחמים', emoji: '🫓' },
  { name: 'טורטייה', calories: 120, protein: 3, fat: 3, carbs: 20, portion: 'יחידה', category: 'לחמים', emoji: '🌯' },
  { name: 'אורז לבן מבושל', calories: 200, protein: 4, fat: 0, carbs: 45, portion: 'כוס', category: 'לחמים', emoji: '🍚' },
  { name: 'אורז חום מבושל', calories: 215, protein: 5, fat: 2, carbs: 44, portion: 'כוס', category: 'לחמים', emoji: '🍚' },
  { name: 'פסטה מבושלת', calories: 220, protein: 8, fat: 1, carbs: 43, portion: 'כוס', category: 'לחמים', emoji: '🍝' },
  { name: 'קוסקוס', calories: 175, protein: 6, fat: 0, carbs: 36, portion: 'כוס', category: 'לחמים', emoji: '🥣' },
  { name: 'בורגול', calories: 150, protein: 6, fat: 0, carbs: 34, portion: 'כוס', category: 'לחמים', emoji: '🥣' },
  { name: 'קינואה', calories: 220, protein: 8, fat: 4, carbs: 39, portion: 'כוס', category: 'לחמים', emoji: '🥣' },
  { name: 'תפוח אדמה אפוי', calories: 160, protein: 4, fat: 0, carbs: 37, portion: 'בינוני', category: 'לחמים', emoji: '🥔' },
  { name: 'פירה', calories: 210, protein: 4, fat: 8, carbs: 30, portion: 'כוס', category: 'לחמים', emoji: '🥔' },
  { name: 'בטטה אפויה', calories: 115, protein: 2, fat: 0, carbs: 27, portion: 'בינונית', category: 'לחמים', emoji: '🍠' },
  { name: 'קורנפלקס', calories: 110, protein: 2, fat: 0, carbs: 26, portion: 'כוס', category: 'לחמים', emoji: '🥣' },
  { name: 'גרנולה', calories: 300, protein: 7, fat: 12, carbs: 40, portion: 'חצי כוס', category: 'לחמים', emoji: '🥣' },
  { name: 'שקדי מרק', calories: 45, protein: 1, fat: 2, carbs: 6, portion: 'כף', category: 'לחמים', emoji: '🍜' },
  { name: 'לחם שום', calories: 180, protein: 4, fat: 7, carbs: 24, portion: 'פרוסה', category: 'לחמים', emoji: '🧄' },
  { name: 'חלה', calories: 200, protein: 5, fat: 4, carbs: 35, portion: 'פרוסה', category: 'לחמים', emoji: '🍞' },
  { name: 'פנקייק', calories: 175, protein: 5, fat: 5, carbs: 27, portion: 'יחידה', category: 'לחמים', emoji: '🥞' },
  { name: 'ופל', calories: 220, protein: 5, fat: 8, carbs: 30, portion: 'יחידה', category: 'לחמים', emoji: '🧇' },
  { name: 'נודלס אטריות', calories: 190, protein: 7, fat: 1, carbs: 38, portion: 'כוס', category: 'לחמים', emoji: '🍜' },
  { name: 'לזניה', calories: 350, protein: 18, fat: 14, carbs: 36, portion: 'מנה', category: 'לחמים', emoji: '🍝' },
  { name: 'רביולי', calories: 280, protein: 12, fat: 8, carbs: 38, portion: 'מנה', category: 'לחמים', emoji: '🥟' },
  { name: 'פתיתים', calories: 200, protein: 7, fat: 1, carbs: 40, portion: 'כוס', category: 'לחמים', emoji: '🍝' },

  // חלבון - בשר ודגים
  { name: 'חזה עוף צלוי', calories: 165, protein: 31, fat: 4, carbs: 0, portion: '100 גרם', category: 'חלבון', emoji: '🍗' },
  { name: 'שניצל עוף מטוגן', calories: 280, protein: 20, fat: 14, carbs: 16, portion: '100 גרם', category: 'חלבון', emoji: '🍗' },
  { name: 'שניצל עוף אפוי', calories: 200, protein: 25, fat: 6, carbs: 10, portion: '100 גרם', category: 'חלבון', emoji: '🍗' },
  { name: 'כרעיים עוף', calories: 210, protein: 26, fat: 11, carbs: 0, portion: '100 גרם', category: 'חלבון', emoji: '🍗' },
  { name: 'סטייק בקר', calories: 270, protein: 26, fat: 18, carbs: 0, portion: '100 גרם', category: 'חלבון', emoji: '🥩' },
  { name: 'המבורגר (קציצה)', calories: 250, protein: 20, fat: 17, carbs: 3, portion: '100 גרם', category: 'חלבון', emoji: '🥩' },
  { name: 'קבב', calories: 230, protein: 18, fat: 15, carbs: 5, portion: '100 גרם', category: 'חלבון', emoji: '🥩' },
  { name: 'שווארמה', calories: 280, protein: 22, fat: 18, carbs: 6, portion: 'מנה', category: 'חלבון', emoji: '🥙' },
  { name: 'דג סלמון', calories: 210, protein: 22, fat: 13, carbs: 0, portion: '100 גרם', category: 'חלבון', emoji: '🐟' },
  { name: 'דג טונה (שימורים)', calories: 115, protein: 25, fat: 1, carbs: 0, portion: 'פחית קטנה', category: 'חלבון', emoji: '🐟' },
  { name: 'דג אמנון/מושט', calories: 130, protein: 26, fat: 3, carbs: 0, portion: '100 גרם', category: 'חלבון', emoji: '🐟' },
  { name: 'ביצה מבושלת', calories: 75, protein: 6, fat: 5, carbs: 1, portion: 'יחידה', category: 'חלבון', emoji: '🥚' },
  { name: 'ביצה מטוגנת', calories: 95, protein: 6, fat: 7, carbs: 1, portion: 'יחידה', category: 'חלבון', emoji: '🍳' },
  { name: 'חביתה (2 ביצים)', calories: 190, protein: 13, fat: 14, carbs: 2, portion: 'מנה', category: 'חלבון', emoji: '🍳' },
  { name: 'שקשוקה (2 ביצים)', calories: 250, protein: 14, fat: 15, carbs: 14, portion: 'מנה', category: 'חלבון', emoji: '🍳' },
  { name: 'טופו', calories: 80, protein: 8, fat: 5, carbs: 2, portion: '100 גרם', category: 'חלבון', emoji: '🧈' },
  { name: 'נקניקייה', calories: 180, protein: 7, fat: 16, carbs: 2, portion: 'יחידה', category: 'חלבון', emoji: '🌭' },
  { name: 'נקניק הודו', calories: 60, protein: 9, fat: 2, carbs: 2, portion: '3 פרוסות', category: 'חלבון', emoji: '🥓' },
  { name: 'פרגית צלויה', calories: 190, protein: 27, fat: 9, carbs: 0, portion: '100 גרם', category: 'חלבון', emoji: '🍗' },
  { name: 'כבד עוף', calories: 170, protein: 25, fat: 6, carbs: 3, portion: '100 גרם', category: 'חלבון', emoji: '🍖' },
  { name: 'דג דניס', calories: 145, protein: 24, fat: 5, carbs: 0, portion: '100 גרם', category: 'חלבון', emoji: '🐟' },
  { name: 'שרימפס', calories: 100, protein: 20, fat: 1, carbs: 1, portion: '100 גרם', category: 'חלבון', emoji: '🦐' },
  { name: 'אנטריקוט', calories: 300, protein: 25, fat: 22, carbs: 0, portion: '100 גרם', category: 'חלבון', emoji: '🥩' },
  { name: 'צלי בקר', calories: 240, protein: 28, fat: 14, carbs: 0, portion: '100 גרם', category: 'חלבון', emoji: '🥩' },
  { name: 'עוף שלם (שוק)', calories: 230, protein: 24, fat: 14, carbs: 0, portion: '100 גרם', category: 'חלבון', emoji: '🍗' },
  { name: 'חומוס (חלבון)', calories: 120, protein: 7, fat: 3, carbs: 17, portion: 'כוס', category: 'חלבון', emoji: '🫘' },
  { name: 'עדשים מבושלות', calories: 230, protein: 18, fat: 1, carbs: 40, portion: 'כוס', category: 'חלבון', emoji: '🫘' },
  { name: 'שעועית אדומה', calories: 220, protein: 15, fat: 1, carbs: 40, portion: 'כוס', category: 'חלבון', emoji: '🫘' },
  { name: 'אדממה', calories: 120, protein: 12, fat: 5, carbs: 9, portion: 'כוס', category: 'חלבון', emoji: '🫛' },

  // מוצרי חלב
  { name: 'חלב 3%', calories: 60, protein: 3, fat: 3, carbs: 5, portion: 'כוס', category: 'חלב', emoji: '🥛' },
  { name: 'חלב 1%', calories: 45, protein: 3, fat: 1, carbs: 5, portion: 'כוס', category: 'חלב', emoji: '🥛' },
  { name: 'יוגורט רגיל', calories: 65, protein: 4, fat: 2, carbs: 8, portion: 'כוס', category: 'חלב', emoji: '🥛' },
  { name: 'יוגורט יווני', calories: 100, protein: 10, fat: 5, carbs: 4, portion: 'כוס', category: 'חלב', emoji: '🥛' },
  { name: 'קוטג\' 5%', calories: 100, protein: 12, fat: 5, carbs: 3, portion: 'כוס', category: 'חלב', emoji: '🧀' },
  { name: 'גבינה לבנה 5%', calories: 80, protein: 10, fat: 5, carbs: 1, portion: '100 גרם', category: 'חלב', emoji: '🧀' },
  { name: 'גבינה צהובה', calories: 105, protein: 7, fat: 8, carbs: 1, portion: 'פרוסה', category: 'חלב', emoji: '🧀' },
  { name: 'גבינת שמנת', calories: 50, protein: 1, fat: 5, carbs: 1, portion: 'כף', category: 'חלב', emoji: '🧀' },
  { name: 'לבנה', calories: 70, protein: 5, fat: 5, carbs: 2, portion: '100 גרם', category: 'חלב', emoji: '🧀' },
  { name: 'שוקו', calories: 160, protein: 6, fat: 4, carbs: 24, portion: 'כוס', category: 'חלב', emoji: '🍫' },
  { name: 'מילקשייק', calories: 350, protein: 8, fat: 12, carbs: 52, portion: 'כוס גדולה', category: 'חלב', emoji: '🥤' },
  { name: 'חלב שקדים', calories: 30, protein: 1, fat: 2, carbs: 1, portion: 'כוס', category: 'חלב', emoji: '🥛' },
  { name: 'חלב סויה', calories: 80, protein: 7, fat: 4, carbs: 4, portion: 'כוס', category: 'חלב', emoji: '🥛' },
  { name: 'חלב קוקוס', calories: 45, protein: 0, fat: 4, carbs: 2, portion: 'כוס', category: 'חלב', emoji: '🥥' },
  { name: 'שמנת מתוקה', calories: 50, protein: 0, fat: 5, carbs: 1, portion: 'כף', category: 'חלב', emoji: '🍦' },
  { name: 'שמנת חמוצה', calories: 30, protein: 0, fat: 3, carbs: 1, portion: 'כף', category: 'חלב', emoji: '🍦' },
  { name: 'מוצרלה', calories: 280, protein: 22, fat: 20, carbs: 3, portion: '100 גרם', category: 'חלב', emoji: '🧀' },
  { name: 'פרמזן', calories: 110, protein: 10, fat: 7, carbs: 1, portion: '30 גרם', category: 'חלב', emoji: '🧀' },
  { name: 'גבינת עיזים', calories: 100, protein: 6, fat: 8, carbs: 1, portion: '30 גרם', category: 'חלב', emoji: '🧀' },
  { name: 'פודינג', calories: 150, protein: 3, fat: 4, carbs: 25, portion: 'כוס', category: 'חלב', emoji: '🍮' },

  // ירקות
  { name: 'סלט ירקות (ללא רוטב)', calories: 35, protein: 2, fat: 0, carbs: 7, portion: 'צלחת', category: 'ירקות', emoji: '🥗' },
  { name: 'סלט ירקות עם שמן זית', calories: 100, protein: 2, fat: 7, carbs: 7, portion: 'צלחת', category: 'ירקות', emoji: '🥗' },
  { name: 'עגבנייה', calories: 25, protein: 1, fat: 0, carbs: 5, portion: 'בינונית', category: 'ירקות', emoji: '🍅' },
  { name: 'מלפפון', calories: 15, protein: 1, fat: 0, carbs: 3, portion: 'בינוני', category: 'ירקות', emoji: '🥒' },
  { name: 'גזר', calories: 30, protein: 1, fat: 0, carbs: 7, portion: 'בינוני', category: 'ירקות', emoji: '🥕' },
  { name: 'פלפל', calories: 25, protein: 1, fat: 0, carbs: 5, portion: 'בינוני', category: 'ירקות', emoji: '🫑' },
  { name: 'בצל', calories: 45, protein: 1, fat: 0, carbs: 10, portion: 'בינוני', category: 'ירקות', emoji: '🧅' },
  { name: 'ברוקולי מבושל', calories: 55, protein: 4, fat: 1, carbs: 10, portion: 'כוס', category: 'ירקות', emoji: '🥦' },
  { name: 'תירס', calories: 90, protein: 3, fat: 1, carbs: 19, portion: 'קלח', category: 'ירקות', emoji: '🌽' },
  { name: 'חציל צלוי', calories: 60, protein: 1, fat: 2, carbs: 10, portion: 'כוס', category: 'ירקות', emoji: '🍆' },
  { name: 'קישוא', calories: 20, protein: 1, fat: 0, carbs: 4, portion: 'בינוני', category: 'ירקות', emoji: '🥒' },
  { name: 'אבוקדו', calories: 240, protein: 3, fat: 22, carbs: 12, portion: 'חצי', category: 'ירקות', emoji: '🥑' },
  { name: 'חסה', calories: 10, protein: 1, fat: 0, carbs: 2, portion: 'כוס', category: 'ירקות', emoji: '🥬' },
  { name: 'כרוב', calories: 25, protein: 1, fat: 0, carbs: 5, portion: 'כוס', category: 'ירקות', emoji: '🥬' },
  { name: 'תרד', calories: 7, protein: 1, fat: 0, carbs: 1, portion: 'כוס', category: 'ירקות', emoji: '🥬' },
  { name: 'שעועית ירוקה', calories: 35, protein: 2, fat: 0, carbs: 7, portion: 'כוס', category: 'ירקות', emoji: '🫛' },
  { name: 'אפונה', calories: 60, protein: 4, fat: 0, carbs: 11, portion: 'כוס', category: 'ירקות', emoji: '🫛' },
  { name: 'פטריות', calories: 15, protein: 2, fat: 0, carbs: 2, portion: 'כוס', category: 'ירקות', emoji: '🍄' },
  { name: 'סלרי', calories: 10, protein: 0, fat: 0, carbs: 2, portion: 'גבעול', category: 'ירקות', emoji: '🥬' },
  { name: 'צנונית', calories: 5, protein: 0, fat: 0, carbs: 1, portion: 'יחידה', category: 'ירקות', emoji: '🔴' },
  { name: 'סלק', calories: 60, protein: 2, fat: 0, carbs: 13, portion: 'בינוני', category: 'ירקות', emoji: '🟣' },
  { name: 'כרובית', calories: 25, protein: 2, fat: 0, carbs: 5, portion: 'כוס', category: 'ירקות', emoji: '🥦' },
  { name: 'דלעת', calories: 30, protein: 1, fat: 0, carbs: 7, portion: 'כוס', category: 'ירקות', emoji: '🎃' },
  { name: 'עגבניות שרי', calories: 30, protein: 1, fat: 0, carbs: 6, portion: 'כוס', category: 'ירקות', emoji: '🍅' },
  { name: 'פלפל חריף', calories: 20, protein: 1, fat: 0, carbs: 4, portion: 'יחידה', category: 'ירקות', emoji: '🌶️' },
  { name: 'שום', calories: 5, protein: 0, fat: 0, carbs: 1, portion: 'שן', category: 'ירקות', emoji: '🧄' },

  // פירות
  { name: 'תפוח', calories: 95, protein: 0, fat: 0, carbs: 25, portion: 'בינוני', category: 'פירות', emoji: '🍎' },
  { name: 'בננה', calories: 105, protein: 1, fat: 0, carbs: 27, portion: 'בינונית', category: 'פירות', emoji: '🍌' },
  { name: 'תפוז', calories: 60, protein: 1, fat: 0, carbs: 15, portion: 'בינוני', category: 'פירות', emoji: '🍊' },
  { name: 'אשכולית', calories: 50, protein: 1, fat: 0, carbs: 13, portion: 'חצי', category: 'פירות', emoji: '🍊' },
  { name: 'ענבים', calories: 60, protein: 1, fat: 0, carbs: 15, portion: 'כוס', category: 'פירות', emoji: '🍇' },
  { name: 'אבטיח', calories: 85, protein: 2, fat: 0, carbs: 21, portion: '2 פרוסות', category: 'פירות', emoji: '🍉' },
  { name: 'מלון', calories: 55, protein: 1, fat: 0, carbs: 13, portion: '2 פרוסות', category: 'פירות', emoji: '🍈' },
  { name: 'תמרים', calories: 280, protein: 2, fat: 0, carbs: 70, portion: '100 גרם', category: 'פירות', emoji: '🌴' },
  { name: 'תותים', calories: 50, protein: 1, fat: 0, carbs: 12, portion: 'כוס', category: 'פירות', emoji: '🍓' },
  { name: 'מנגו', calories: 100, protein: 1, fat: 0, carbs: 25, portion: 'חצי', category: 'פירות', emoji: '🥭' },
  { name: 'אפרסק', calories: 60, protein: 1, fat: 0, carbs: 14, portion: 'בינוני', category: 'פירות', emoji: '🍑' },
  { name: 'שזיף', calories: 30, protein: 0, fat: 0, carbs: 8, portion: 'יחידה', category: 'פירות', emoji: '🟣' },
  { name: 'אננס', calories: 80, protein: 1, fat: 0, carbs: 20, portion: 'כוס', category: 'פירות', emoji: '🍍' },
  { name: 'קיווי', calories: 45, protein: 1, fat: 0, carbs: 11, portion: 'יחידה', category: 'פירות', emoji: '🥝' },
  { name: 'אגס', calories: 100, protein: 1, fat: 0, carbs: 25, portion: 'בינוני', category: 'פירות', emoji: '🍐' },
  { name: 'דובדבנים', calories: 90, protein: 1, fat: 0, carbs: 22, portion: 'כוס', category: 'פירות', emoji: '🍒' },
  { name: 'לימון', calories: 15, protein: 0, fat: 0, carbs: 4, portion: 'יחידה', category: 'פירות', emoji: '🍋' },
  { name: 'רימון', calories: 80, protein: 1, fat: 1, carbs: 18, portion: 'חצי', category: 'פירות', emoji: '🔴' },
  { name: 'פסיפלורה', calories: 20, protein: 0, fat: 0, carbs: 5, portion: 'יחידה', category: 'פירות', emoji: '🟡' },
  { name: 'קלמנטינה', calories: 35, protein: 1, fat: 0, carbs: 9, portion: 'יחידה', category: 'פירות', emoji: '🍊' },
  { name: 'פטל', calories: 65, protein: 1, fat: 1, carbs: 15, portion: 'כוס', category: 'פירות', emoji: '🫐' },
  { name: 'אוכמניות', calories: 85, protein: 1, fat: 0, carbs: 21, portion: 'כוס', category: 'פירות', emoji: '🫐' },
  { name: 'קוקוס טרי', calories: 160, protein: 2, fat: 15, carbs: 6, portion: 'חתיכה', category: 'פירות', emoji: '🥥' },
  { name: 'פירות יבשים מיקס', calories: 240, protein: 3, fat: 1, carbs: 58, portion: 'קומץ', category: 'פירות', emoji: '🍇' },

  // מאכלים ישראליים
  { name: 'חומוס', calories: 170, protein: 8, fat: 8, carbs: 16, portion: 'צלחת קטנה', category: 'ישראלי', emoji: '🫘' },
  { name: 'פלאפל (5 כדורים)', calories: 330, protein: 13, fat: 18, carbs: 28, portion: 'מנה', category: 'ישראלי', emoji: '🧆' },
  { name: 'פלאפל בפיתה', calories: 550, protein: 18, fat: 22, carbs: 62, portion: 'מנה', category: 'ישראלי', emoji: '🧆' },
  { name: 'שווארמה בפיתה', calories: 650, protein: 35, fat: 28, carbs: 58, portion: 'מנה', category: 'ישראלי', emoji: '🥙' },
  { name: 'שווארמה בלאפה', calories: 750, protein: 38, fat: 32, carbs: 68, portion: 'מנה', category: 'ישראלי', emoji: '🥙' },
  { name: 'סביח', calories: 600, protein: 16, fat: 30, carbs: 60, portion: 'מנה', category: 'ישראלי', emoji: '🥙' },
  { name: 'טחינה', calories: 90, protein: 3, fat: 8, carbs: 3, portion: 'כף', category: 'ישראלי', emoji: '🥣' },
  { name: 'חומוס עם בשר', calories: 450, protein: 28, fat: 22, carbs: 30, portion: 'צלחת', category: 'ישראלי', emoji: '🫘' },
  { name: 'מעדה', calories: 300, protein: 10, fat: 14, carbs: 32, portion: 'צלחת', category: 'ישראלי', emoji: '🍲' },
  { name: 'ג\'חנון', calories: 400, protein: 8, fat: 18, carbs: 50, portion: 'יחידה', category: 'ישראלי', emoji: '🫓' },
  { name: 'מלאווח', calories: 350, protein: 7, fat: 16, carbs: 42, portion: 'יחידה', category: 'ישראלי', emoji: '🫓' },
  { name: 'בורקס גבינה', calories: 350, protein: 10, fat: 20, carbs: 30, portion: 'יחידה', category: 'ישראלי', emoji: '🥐' },
  { name: 'בורקס תפו"א', calories: 300, protein: 5, fat: 16, carbs: 34, portion: 'יחידה', category: 'ישראלי', emoji: '🥐' },
  { name: 'לחוח', calories: 100, protein: 3, fat: 1, carbs: 20, portion: 'יחידה', category: 'ישראלי', emoji: '🫓' },
  { name: 'מרק עוף', calories: 80, protein: 6, fat: 3, carbs: 7, portion: 'צלחת', category: 'ישראלי', emoji: '🍲' },
  { name: 'מרק עדשים', calories: 180, protein: 12, fat: 3, carbs: 27, portion: 'צלחת', category: 'ישראלי', emoji: '🍲' },
  { name: 'חריימה', calories: 200, protein: 22, fat: 8, carbs: 10, portion: 'מנה', category: 'ישראלי', emoji: '🍲' },
  { name: 'קובה', calories: 250, protein: 12, fat: 10, carbs: 28, portion: '2 יחידות', category: 'ישראלי', emoji: '🥟' },
  { name: 'שקשוקה ירוקה', calories: 220, protein: 12, fat: 14, carbs: 10, portion: 'מנה', category: 'ישראלי', emoji: '🍳' },
  { name: 'חמין/צ\'ולנט', calories: 450, protein: 25, fat: 20, carbs: 40, portion: 'צלחת', category: 'ישראלי', emoji: '🍲' },
  { name: 'מפרום', calories: 280, protein: 14, fat: 12, carbs: 28, portion: 'מנה', category: 'ישראלי', emoji: '🥔' },
  { name: 'כרוב ממולא', calories: 200, protein: 10, fat: 8, carbs: 22, portion: '2 יחידות', category: 'ישראלי', emoji: '🥬' },
  { name: 'פילפל ממולא', calories: 250, protein: 12, fat: 10, carbs: 26, portion: 'יחידה', category: 'ישראלי', emoji: '🫑' },
  { name: 'קוגל תפו"א', calories: 280, protein: 5, fat: 14, carbs: 32, portion: 'מנה', category: 'ישראלי', emoji: '🥔' },
  { name: 'סלט חצילים', calories: 120, protein: 2, fat: 8, carbs: 10, portion: 'מנה', category: 'ישראלי', emoji: '🍆' },
  { name: 'מטבוחה', calories: 60, protein: 1, fat: 3, carbs: 7, portion: 'מנה', category: 'ישראלי', emoji: '🍅' },
  { name: 'סחוג', calories: 10, protein: 0, fat: 1, carbs: 1, portion: 'כפית', category: 'ישראלי', emoji: '🌶️' },
  { name: 'עמבה', calories: 15, protein: 0, fat: 0, carbs: 4, portion: 'כף', category: 'ישראלי', emoji: '🥭' },
  { name: 'שיפודי עוף', calories: 180, protein: 28, fat: 7, carbs: 1, portion: '2 שיפודים', category: 'ישראלי', emoji: '🍢' },
  { name: 'שיפודי פרגית', calories: 200, protein: 26, fat: 10, carbs: 1, portion: '2 שיפודים', category: 'ישראלי', emoji: '🍢' },
  { name: 'סלט טאבולה', calories: 110, protein: 3, fat: 5, carbs: 14, portion: 'צלחת', category: 'ישראלי', emoji: '🥗' },
  { name: 'סלט פטוש', calories: 130, protein: 3, fat: 6, carbs: 16, portion: 'צלחת', category: 'ישראלי', emoji: '🥗' },
  { name: 'לביבות תפו"א', calories: 180, protein: 3, fat: 10, carbs: 20, portion: '2 יחידות', category: 'ישראלי', emoji: '🥔' },
  { name: 'כנאפה', calories: 350, protein: 8, fat: 14, carbs: 46, portion: 'מנה', category: 'ישראלי', emoji: '🧁' },
  { name: 'בקלאווה', calories: 250, protein: 4, fat: 12, carbs: 32, portion: '2 חתיכות', category: 'ישראלי', emoji: '🍯' },

  // חטיפים ומתוקים
  { name: 'במבה', calories: 130, protein: 3, fat: 7, carbs: 14, portion: 'שקית קטנה', category: 'חטיפים', emoji: '🥜' },
  { name: 'ביסלי', calories: 130, protein: 2, fat: 5, carbs: 19, portion: 'שקית קטנה', category: 'חטיפים', emoji: '🍿' },
  { name: 'צ\'יפס', calories: 150, protein: 2, fat: 9, carbs: 15, portion: 'שקית קטנה', category: 'חטיפים', emoji: '🍟' },
  { name: 'פופקורן', calories: 100, protein: 3, fat: 5, carbs: 12, portion: 'כוס', category: 'חטיפים', emoji: '🍿' },
  { name: 'שוקולד חלב', calories: 230, protein: 3, fat: 13, carbs: 25, portion: 'חפיסה (45 גרם)', category: 'חטיפים', emoji: '🍫' },
  { name: 'שוקולד מריר', calories: 200, protein: 3, fat: 13, carbs: 18, portion: 'חפיסה (40 גרם)', category: 'חטיפים', emoji: '🍫' },
  { name: 'עוגיית שוקולד צ\'יפס', calories: 80, protein: 1, fat: 4, carbs: 10, portion: 'יחידה', category: 'חטיפים', emoji: '🍪' },
  { name: 'קרואסון', calories: 230, protein: 4, fat: 12, carbs: 26, portion: 'יחידה', category: 'חטיפים', emoji: '🥐' },
  { name: 'עוגת שוקולד', calories: 350, protein: 5, fat: 17, carbs: 44, portion: 'פרוסה', category: 'חטיפים', emoji: '🍰' },
  { name: 'גלידה', calories: 200, protein: 3, fat: 10, carbs: 24, portion: 'כדור', category: 'חטיפים', emoji: '🍦' },
  { name: 'סופגנייה', calories: 300, protein: 4, fat: 14, carbs: 38, portion: 'יחידה', category: 'חטיפים', emoji: '🍩' },
  { name: 'חלווה', calories: 140, protein: 4, fat: 8, carbs: 14, portion: '30 גרם', category: 'חטיפים', emoji: '🍬' },
  { name: 'שקדים', calories: 170, protein: 6, fat: 15, carbs: 3, portion: 'קומץ (30 גרם)', category: 'חטיפים', emoji: '🥜' },
  { name: 'אגוזי מלך', calories: 185, protein: 4, fat: 18, carbs: 2, portion: 'קומץ (30 גרם)', category: 'חטיפים', emoji: '🥜' },
  { name: 'חמאת בוטנים', calories: 95, protein: 4, fat: 8, carbs: 3, portion: 'כף', category: 'חטיפים', emoji: '🥜' },
  { name: 'חטיף אנרגיה', calories: 200, protein: 5, fat: 7, carbs: 30, portion: 'יחידה', category: 'חטיפים', emoji: '🍫' },
  { name: 'מאפין שוקולד', calories: 380, protein: 5, fat: 18, carbs: 48, portion: 'יחידה', category: 'חטיפים', emoji: '🧁' },
  { name: 'דונאט', calories: 250, protein: 3, fat: 12, carbs: 32, portion: 'יחידה', category: 'חטיפים', emoji: '🍩' },
  { name: 'בוטנים קלויים', calories: 160, protein: 7, fat: 14, carbs: 3, portion: 'קומץ (30 גרם)', category: 'חטיפים', emoji: '🥜' },
  { name: 'קשיו', calories: 155, protein: 5, fat: 12, carbs: 8, portion: 'קומץ (30 גרם)', category: 'חטיפים', emoji: '🥜' },
  { name: 'פיסטוקים', calories: 160, protein: 6, fat: 13, carbs: 5, portion: 'קומץ (30 גרם)', category: 'חטיפים', emoji: '🥜' },
  { name: 'חטיף גרנולה', calories: 120, protein: 2, fat: 4, carbs: 20, portion: 'יחידה', category: 'חטיפים', emoji: '🥣' },
  { name: 'סוכריות גומי', calories: 130, protein: 2, fat: 0, carbs: 32, portion: 'קומץ', category: 'חטיפים', emoji: '🍬' },
  { name: 'עוגיות חמאה', calories: 70, protein: 1, fat: 3, carbs: 10, portion: 'יחידה', category: 'חטיפים', emoji: '🍪' },
  { name: 'טירמיסו', calories: 350, protein: 6, fat: 20, carbs: 34, portion: 'מנה', category: 'חטיפים', emoji: '🍰' },
  { name: 'קרם ברולה', calories: 300, protein: 4, fat: 18, carbs: 30, portion: 'מנה', category: 'חטיפים', emoji: '🍮' },
  { name: 'שטרודל תפוחים', calories: 280, protein: 3, fat: 12, carbs: 40, portion: 'פרוסה', category: 'חטיפים', emoji: '🥧' },
  { name: 'עוגת גבינה', calories: 320, protein: 6, fat: 20, carbs: 28, portion: 'פרוסה', category: 'חטיפים', emoji: '🍰' },
  { name: 'פופסיקל/ארטיק', calories: 80, protein: 0, fat: 0, carbs: 20, portion: 'יחידה', category: 'חטיפים', emoji: '🍦' },

  // משקאות
  { name: 'קפה שחור', calories: 5, protein: 0, fat: 0, carbs: 1, portion: 'כוס', category: 'משקאות', emoji: '☕' },
  { name: 'קפה עם חלב', calories: 30, protein: 1, fat: 1, carbs: 3, portion: 'כוס', category: 'משקאות', emoji: '☕' },
  { name: 'קפוצ\'ינו', calories: 120, protein: 6, fat: 4, carbs: 12, portion: 'כוס', category: 'משקאות', emoji: '☕' },
  { name: 'לאטה', calories: 150, protein: 8, fat: 5, carbs: 15, portion: 'כוס גדולה', category: 'משקאות', emoji: '☕' },
  { name: 'תה', calories: 0, protein: 0, fat: 0, carbs: 0, portion: 'כוס', category: 'משקאות', emoji: '🍵' },
  { name: 'מיץ תפוזים טבעי', calories: 110, protein: 2, fat: 0, carbs: 26, portion: 'כוס', category: 'משקאות', emoji: '🧃' },
  { name: 'קולה', calories: 140, protein: 0, fat: 0, carbs: 35, portion: 'פחית', category: 'משקאות', emoji: '🥤' },
  { name: 'קולה זירו', calories: 0, protein: 0, fat: 0, carbs: 0, portion: 'פחית', category: 'משקאות', emoji: '🥤' },
  { name: 'בירה', calories: 150, protein: 1, fat: 0, carbs: 13, portion: 'פחית', category: 'משקאות', emoji: '🍺' },
  { name: 'יין אדום', calories: 125, protein: 0, fat: 0, carbs: 4, portion: 'כוס', category: 'משקאות', emoji: '🍷' },
  { name: 'סמוזי פירות', calories: 200, protein: 2, fat: 1, carbs: 46, portion: 'כוס', category: 'משקאות', emoji: '🥤' },
  { name: 'מים', calories: 0, protein: 0, fat: 0, carbs: 0, portion: 'כוס', category: 'משקאות', emoji: '💧' },
  { name: 'מיץ גזר', calories: 95, protein: 2, fat: 0, carbs: 22, portion: 'כוס', category: 'משקאות', emoji: '🧃' },
  { name: 'מיץ תפוחים', calories: 115, protein: 0, fat: 0, carbs: 28, portion: 'כוס', category: 'משקאות', emoji: '🧃' },
  { name: 'לימונדה', calories: 100, protein: 0, fat: 0, carbs: 25, portion: 'כוס', category: 'משקאות', emoji: '🍋' },
  { name: 'אייס קפה', calories: 180, protein: 3, fat: 6, carbs: 28, portion: 'כוס', category: 'משקאות', emoji: '🧊' },
  { name: 'אספרסו', calories: 5, protein: 0, fat: 0, carbs: 1, portion: 'כוסית', category: 'משקאות', emoji: '☕' },
  { name: 'תה ירוק', calories: 0, protein: 0, fat: 0, carbs: 0, portion: 'כוס', category: 'משקאות', emoji: '🍵' },
  { name: 'משקה אנרגיה', calories: 110, protein: 0, fat: 0, carbs: 27, portion: 'פחית', category: 'משקאות', emoji: '⚡' },
  { name: 'יין לבן', calories: 120, protein: 0, fat: 0, carbs: 4, portion: 'כוס', category: 'משקאות', emoji: '🥂' },
  { name: 'ערק', calories: 100, protein: 0, fat: 0, carbs: 0, portion: 'כוסית', category: 'משקאות', emoji: '🥃' },
  { name: 'וודקה', calories: 100, protein: 0, fat: 0, carbs: 0, portion: 'כוסית', category: 'משקאות', emoji: '🥃' },

  // מזון מהיר
  { name: 'פיצה מרגריטה', calories: 270, protein: 12, fat: 10, carbs: 33, portion: 'משולש', category: 'מזון מהיר', emoji: '🍕' },
  { name: 'המבורגר עם לחמנייה', calories: 450, protein: 25, fat: 22, carbs: 35, portion: 'מנה', category: 'מזון מהיר', emoji: '🍔' },
  { name: 'צ\'יפס (מנה גדולה)', calories: 400, protein: 4, fat: 20, carbs: 48, portion: 'מנה', category: 'מזון מהיר', emoji: '🍟' },
  { name: 'נאגטס (6)', calories: 280, protein: 14, fat: 16, carbs: 18, portion: '6 יחידות', category: 'מזון מהיר', emoji: '🍗' },
  { name: 'שניצלון', calories: 150, protein: 8, fat: 8, carbs: 12, portion: 'יחידה', category: 'מזון מהיר', emoji: '🍗' },
  { name: 'טוסט גבינה', calories: 300, protein: 14, fat: 16, carbs: 24, portion: 'יחידה', category: 'מזון מהיר', emoji: '🧀' },
  { name: 'סנדוויץ\' טונה', calories: 350, protein: 20, fat: 14, carbs: 34, portion: 'יחידה', category: 'מזון מהיר', emoji: '🥪' },
  { name: 'סנדוויץ\' חזה עוף', calories: 380, protein: 28, fat: 12, carbs: 36, portion: 'יחידה', category: 'מזון מהיר', emoji: '🥪' },
  { name: 'סושי (8 חתיכות)', calories: 350, protein: 14, fat: 6, carbs: 58, portion: 'מנה', category: 'מזון מהיר', emoji: '🍱' },
  { name: 'הוט דוג', calories: 300, protein: 10, fat: 18, carbs: 22, portion: 'יחידה', category: 'מזון מהיר', emoji: '🌭' },
  { name: 'קסדייה', calories: 350, protein: 15, fat: 18, carbs: 28, portion: 'יחידה', category: 'מזון מהיר', emoji: '🌮' },
  { name: 'טאקו', calories: 200, protein: 10, fat: 10, carbs: 16, portion: 'יחידה', category: 'מזון מהיר', emoji: '🌮' },
  { name: 'בוריטו', calories: 550, protein: 24, fat: 20, carbs: 62, portion: 'יחידה', category: 'מזון מהיר', emoji: '🌯' },
  { name: 'פיצה פפרוני', calories: 310, protein: 14, fat: 14, carbs: 30, portion: 'משולש', category: 'מזון מהיר', emoji: '🍕' },
  { name: 'כריך שווארמה', calories: 500, protein: 30, fat: 22, carbs: 42, portion: 'יחידה', category: 'מזון מהיר', emoji: '🥙' },
  { name: 'ספרינג רול', calories: 120, protein: 4, fat: 5, carbs: 14, portion: '2 יחידות', category: 'מזון מהיר', emoji: '🥟' },
  { name: 'דים סאם', calories: 180, protein: 8, fat: 7, carbs: 20, portion: '4 יחידות', category: 'מזון מהיר', emoji: '🥟' },
  { name: 'פאד תאי', calories: 400, protein: 16, fat: 14, carbs: 50, portion: 'מנה', category: 'מזון מהיר', emoji: '🍜' },
  { name: 'ראמן', calories: 450, protein: 18, fat: 16, carbs: 52, portion: 'מנה', category: 'מזון מהיר', emoji: '🍜' },

  // תוספות ורטבים
  { name: 'שמן זית', calories: 120, protein: 0, fat: 14, carbs: 0, portion: 'כף', category: 'תוספות', emoji: '🫒' },
  { name: 'חמאה', calories: 100, protein: 0, fat: 11, carbs: 0, portion: 'כף', category: 'תוספות', emoji: '🧈' },
  { name: 'מיונז', calories: 95, protein: 0, fat: 10, carbs: 1, portion: 'כף', category: 'תוספות', emoji: '🥫' },
  { name: 'קטשופ', calories: 20, protein: 0, fat: 0, carbs: 5, portion: 'כף', category: 'תוספות', emoji: '🥫' },
  { name: 'סוכר', calories: 50, protein: 0, fat: 0, carbs: 12, portion: 'כפית', category: 'תוספות', emoji: '🍬' },
  { name: 'דבש', calories: 65, protein: 0, fat: 0, carbs: 17, portion: 'כף', category: 'תוספות', emoji: '🍯' },
  { name: 'ריבה', calories: 50, protein: 0, fat: 0, carbs: 13, portion: 'כף', category: 'תוספות', emoji: '🍓' },
  { name: 'נוטלה', calories: 100, protein: 1, fat: 6, carbs: 11, portion: 'כף', category: 'תוספות', emoji: '🍫' },
  { name: 'זיתים', calories: 40, protein: 0, fat: 4, carbs: 2, portion: '10 יחידות', category: 'תוספות', emoji: '🫒' },
  { name: 'אורז עם עדשים (מג\'דרה)', calories: 250, protein: 10, fat: 5, carbs: 42, portion: 'צלחת', category: 'תוספות', emoji: '🍚' },
  { name: 'רוטב סויה', calories: 10, protein: 1, fat: 0, carbs: 1, portion: 'כף', category: 'תוספות', emoji: '🥫' },
  { name: 'חרדל', calories: 5, protein: 0, fat: 0, carbs: 1, portion: 'כפית', category: 'תוספות', emoji: '🟡' },
  { name: 'רוטב ברביקיו', calories: 30, protein: 0, fat: 0, carbs: 7, portion: 'כף', category: 'תוספות', emoji: '🥫' },
  { name: 'פסטו', calories: 80, protein: 2, fat: 7, carbs: 2, portion: 'כף', category: 'תוספות', emoji: '🌿' },
  { name: 'רוטב אלף האיים', calories: 60, protein: 0, fat: 6, carbs: 3, portion: 'כף', category: 'תוספות', emoji: '🥫' },
  { name: 'גואקמולי', calories: 50, protein: 1, fat: 4, carbs: 3, portion: 'כף', category: 'תוספות', emoji: '🥑' },
  { name: 'סלסה', calories: 10, protein: 0, fat: 0, carbs: 2, portion: 'כף', category: 'תוספות', emoji: '🍅' },
  { name: 'חומץ בלסמי', calories: 15, protein: 0, fat: 0, carbs: 3, portion: 'כף', category: 'תוספות', emoji: '🫗' },
  { name: 'טחינה גולמית', calories: 90, protein: 3, fat: 8, carbs: 3, portion: 'כף', category: 'תוספות', emoji: '🥜' },
  { name: 'שמן קנולה', calories: 120, protein: 0, fat: 14, carbs: 0, portion: 'כף', category: 'תוספות', emoji: '🫗' },
  { name: 'ממרח שוקולד', calories: 80, protein: 1, fat: 4, carbs: 10, portion: 'כף', category: 'תוספות', emoji: '🍫' },
  { name: 'חמאת שקדים', calories: 100, protein: 3, fat: 9, carbs: 3, portion: 'כף', category: 'תוספות', emoji: '🥜' },
  { name: 'רוטב צ\'ילי מתוק', calories: 40, protein: 0, fat: 0, carbs: 10, portion: 'כף', category: 'תוספות', emoji: '🌶️' },

  // מרקים
  { name: 'מרק ירקות', calories: 70, protein: 2, fat: 2, carbs: 12, portion: 'צלחת', category: 'מרקים', emoji: '🥣' },
  { name: 'מרק עגבניות', calories: 90, protein: 2, fat: 3, carbs: 14, portion: 'צלחת', category: 'מרקים', emoji: '🍅' },
  { name: 'מרק כרובית', calories: 80, protein: 3, fat: 3, carbs: 10, portion: 'צלחת', category: 'מרקים', emoji: '🥦' },
  { name: 'מרק בצל', calories: 60, protein: 2, fat: 2, carbs: 8, portion: 'צלחת', category: 'מרקים', emoji: '🧅' },
  { name: 'מרק אפונה', calories: 130, protein: 8, fat: 2, carbs: 20, portion: 'צלחת', category: 'מרקים', emoji: '🫛' },
  { name: 'מרק תירס', calories: 140, protein: 3, fat: 4, carbs: 24, portion: 'צלחת', category: 'מרקים', emoji: '🌽' },
  { name: 'מרק פטריות', calories: 100, protein: 3, fat: 5, carbs: 10, portion: 'צלחת', category: 'מרקים', emoji: '🍄' },
  { name: 'מרק קובה', calories: 200, protein: 10, fat: 6, carbs: 26, portion: 'צלחת', category: 'מרקים', emoji: '🥟' },
  { name: 'מרק חרירה', calories: 160, protein: 8, fat: 4, carbs: 22, portion: 'צלחת', category: 'מרקים', emoji: '🍲' },
  { name: 'מרק בטטה', calories: 120, protein: 2, fat: 3, carbs: 22, portion: 'צלחת', category: 'מרקים', emoji: '🍠' },
  { name: 'מרק מינסטרונה', calories: 110, protein: 4, fat: 2, carbs: 18, portion: 'צלחת', category: 'מרקים', emoji: '🍲' },
  { name: 'מרק גזר וג\'ינג\'ר', calories: 85, protein: 1, fat: 3, carbs: 14, portion: 'צלחת', category: 'מרקים', emoji: '🥕' },
  { name: 'מרק עוף עם אטריות', calories: 120, protein: 8, fat: 3, carbs: 14, portion: 'צלחת', category: 'מרקים', emoji: '🍜' },

  // ארוחות בוקר
  { name: 'שיבולת שועל (קוואקר)', calories: 150, protein: 5, fat: 3, carbs: 27, portion: 'כוס', category: 'ארוחת בוקר', emoji: '🥣' },
  { name: 'מוזלי', calories: 200, protein: 5, fat: 6, carbs: 32, portion: 'חצי כוס', category: 'ארוחת בוקר', emoji: '🥣' },
  { name: 'שקשוקה עם גבינה', calories: 320, protein: 18, fat: 20, carbs: 14, portion: 'מנה', category: 'ארוחת בוקר', emoji: '🍳' },
  { name: 'חביתה ירקות', calories: 220, protein: 14, fat: 15, carbs: 6, portion: 'מנה', category: 'ארוחת בוקר', emoji: '🍳' },
  { name: 'ביצה עלומה', calories: 70, protein: 6, fat: 5, carbs: 0, portion: 'יחידה', category: 'ארוחת בוקר', emoji: '🥚' },
  { name: 'ביצים בנדיקט', calories: 350, protein: 16, fat: 24, carbs: 16, portion: 'מנה', category: 'ארוחת בוקר', emoji: '🥚' },
  { name: 'פרנץ\' טוסט', calories: 280, protein: 8, fat: 12, carbs: 34, portion: '2 פרוסות', category: 'ארוחת בוקר', emoji: '🍞' },
  { name: 'אסאי בול', calories: 350, protein: 5, fat: 8, carbs: 62, portion: 'קערה', category: 'ארוחת בוקר', emoji: '🫐' },
  { name: 'סמוזי בול', calories: 300, protein: 6, fat: 6, carbs: 54, portion: 'קערה', category: 'ארוחת בוקר', emoji: '🥝' },
  { name: 'גרנולה עם יוגורט', calories: 350, protein: 12, fat: 12, carbs: 48, portion: 'קערה', category: 'ארוחת בוקר', emoji: '🥣' },
  { name: 'טוסט אבוקדו', calories: 250, protein: 6, fat: 14, carbs: 24, portion: 'יחידה', category: 'ארוחת בוקר', emoji: '🥑' },
  { name: 'בייגל עם גבינת שמנת', calories: 350, protein: 10, fat: 14, carbs: 44, portion: 'יחידה', category: 'ארוחת בוקר', emoji: '🥯' },
  { name: 'קרפ', calories: 200, protein: 5, fat: 8, carbs: 26, portion: 'יחידה', category: 'ארוחת בוקר', emoji: '🥞' },
  { name: 'לחם עם חמאה ודבש', calories: 200, protein: 3, fat: 8, carbs: 28, portion: 'פרוסה', category: 'ארוחת בוקר', emoji: '🍯' },
  { name: 'חלה מתוקה', calories: 220, protein: 5, fat: 5, carbs: 38, portion: 'פרוסה', category: 'ארוחת בוקר', emoji: '🍞' },

  // מנות עיקריות
  { name: 'חזה עוף ברוטב פטריות', calories: 280, protein: 30, fat: 12, carbs: 10, portion: 'מנה', category: 'מנות עיקריות', emoji: '🍗' },
  { name: 'פסטה ברוטב עגבניות', calories: 350, protein: 12, fat: 8, carbs: 56, portion: 'צלחת', category: 'מנות עיקריות', emoji: '🍝' },
  { name: 'פסטה ברוטב שמנת', calories: 450, protein: 14, fat: 20, carbs: 52, portion: 'צלחת', category: 'מנות עיקריות', emoji: '🍝' },
  { name: 'פסטה בולונז', calories: 420, protein: 22, fat: 14, carbs: 48, portion: 'צלחת', category: 'מנות עיקריות', emoji: '🍝' },
  { name: 'סטיר פריי ירקות', calories: 200, protein: 5, fat: 10, carbs: 22, portion: 'מנה', category: 'מנות עיקריות', emoji: '🥘' },
  { name: 'סטיר פריי עוף', calories: 320, protein: 24, fat: 14, carbs: 22, portion: 'מנה', category: 'מנות עיקריות', emoji: '🥘' },
  { name: 'קארי עוף', calories: 380, protein: 28, fat: 18, carbs: 24, portion: 'מנה', category: 'מנות עיקריות', emoji: '🍛' },
  { name: 'קארי ירקות', calories: 250, protein: 6, fat: 12, carbs: 30, portion: 'מנה', category: 'מנות עיקריות', emoji: '🍛' },
  { name: 'דג ברוטב לימון', calories: 220, protein: 26, fat: 10, carbs: 6, portion: 'מנה', category: 'מנות עיקריות', emoji: '🐟' },
  { name: 'דג בתנור', calories: 200, protein: 28, fat: 8, carbs: 4, portion: 'מנה', category: 'מנות עיקריות', emoji: '🐟' },
  { name: 'סלמון בתנור', calories: 280, protein: 26, fat: 18, carbs: 2, portion: 'מנה', category: 'מנות עיקריות', emoji: '🐟' },
  { name: 'חזה הודו צלוי', calories: 150, protein: 30, fat: 3, carbs: 0, portion: '100 גרם', category: 'מנות עיקריות', emoji: '🦃' },
  { name: 'צלעות טלה', calories: 350, protein: 22, fat: 28, carbs: 0, portion: '100 גרם', category: 'מנות עיקריות', emoji: '🍖' },
  { name: 'כבש בתנור', calories: 300, protein: 25, fat: 22, carbs: 0, portion: '100 גרם', category: 'מנות עיקריות', emoji: '🍖' },
  { name: 'עוף בתנור עם ירקות', calories: 320, protein: 28, fat: 14, carbs: 16, portion: 'מנה', category: 'מנות עיקריות', emoji: '🍗' },
  { name: 'מוסקה', calories: 350, protein: 15, fat: 20, carbs: 26, portion: 'מנה', category: 'מנות עיקריות', emoji: '🍆' },
  { name: 'קישקעש (מנהמנה)', calories: 280, protein: 14, fat: 12, carbs: 28, portion: 'מנה', category: 'מנות עיקריות', emoji: '🍳' },
  { name: 'שקדי עוף', calories: 300, protein: 22, fat: 16, carbs: 14, portion: 'מנה', category: 'מנות עיקריות', emoji: '🍗' },
  { name: 'קציצות בקר ברוטב', calories: 350, protein: 24, fat: 18, carbs: 20, portion: '3 יחידות', category: 'מנות עיקריות', emoji: '🥩' },
  { name: 'תבשיל שעועית', calories: 240, protein: 14, fat: 5, carbs: 36, portion: 'צלחת', category: 'מנות עיקריות', emoji: '🫘' },
  { name: 'מקלובה', calories: 400, protein: 20, fat: 16, carbs: 42, portion: 'מנה', category: 'מנות עיקריות', emoji: '🍚' },
  { name: 'אושפלאו (פלוב)', calories: 380, protein: 18, fat: 14, carbs: 44, portion: 'מנה', category: 'מנות עיקריות', emoji: '🍚' },
  { name: 'קוסקוס עם ירקות', calories: 300, protein: 8, fat: 6, carbs: 52, portion: 'צלחת', category: 'מנות עיקריות', emoji: '🥣' },
  { name: 'דג פיש אנד צ\'יפס', calories: 500, protein: 22, fat: 26, carbs: 42, portion: 'מנה', category: 'מנות עיקריות', emoji: '🐟' },
  { name: 'חמין ביצה', calories: 90, protein: 7, fat: 6, carbs: 1, portion: 'יחידה', category: 'מנות עיקריות', emoji: '🥚' },
  { name: 'כושרי', calories: 320, protein: 12, fat: 6, carbs: 54, portion: 'צלחת', category: 'מנות עיקריות', emoji: '🍚' },

  // סלטים
  { name: 'סלט קיסר', calories: 250, protein: 8, fat: 16, carbs: 18, portion: 'צלחת', category: 'סלטים', emoji: '🥗' },
  { name: 'סלט יווני', calories: 200, protein: 6, fat: 14, carbs: 10, portion: 'צלחת', category: 'סלטים', emoji: '🥗' },
  { name: 'סלט טונה', calories: 280, protein: 22, fat: 14, carbs: 14, portion: 'צלחת', category: 'סלטים', emoji: '🥗' },
  { name: 'סלט חזה עוף', calories: 300, protein: 28, fat: 12, carbs: 16, portion: 'צלחת', category: 'סלטים', emoji: '🥗' },
  { name: 'סלט קינואה', calories: 250, protein: 9, fat: 10, carbs: 32, portion: 'צלחת', category: 'סלטים', emoji: '🥗' },
  { name: 'סלט כרוב', calories: 60, protein: 1, fat: 2, carbs: 10, portion: 'צלחת', category: 'סלטים', emoji: '🥬' },
  { name: 'סלט גזר מרוקאי', calories: 80, protein: 1, fat: 4, carbs: 10, portion: 'צלחת', category: 'סלטים', emoji: '🥕' },
  { name: 'סלט חצילים מעושנים', calories: 130, protein: 2, fat: 9, carbs: 10, portion: 'צלחת', category: 'סלטים', emoji: '🍆' },
  { name: 'סלט פסטה', calories: 300, protein: 8, fat: 12, carbs: 40, portion: 'צלחת', category: 'סלטים', emoji: '🍝' },
  { name: 'סלט ניסואז', calories: 280, protein: 18, fat: 16, carbs: 14, portion: 'צלחת', category: 'סלטים', emoji: '🥗' },
  { name: 'סלט עדשים', calories: 200, protein: 12, fat: 6, carbs: 26, portion: 'צלחת', category: 'סלטים', emoji: '🫘' },
  { name: 'סלט אסייתי', calories: 180, protein: 6, fat: 8, carbs: 22, portion: 'צלחת', category: 'סלטים', emoji: '🥗' },
  { name: 'סלט ביצים עם מיונז רגיל', calories: 330, protein: 14, fat: 26, carbs: 6, portion: 'צלחת', category: 'סלטים', emoji: '🥚' },
  { name: 'סלט ביצים עם מיונז דל קלוריות', calories: 220, protein: 14, fat: 14, carbs: 6, portion: 'צלחת', category: 'סלטים', emoji: '🥚' },
  { name: 'סלט ביצים ללא מיונז', calories: 180, protein: 14, fat: 12, carbs: 4, portion: 'צלחת', category: 'סלטים', emoji: '🥚' },
  { name: 'סלט תפו"א עם מיונז רגיל', calories: 360, protein: 4, fat: 22, carbs: 36, portion: 'צלחת', category: 'סלטים', emoji: '🥔' },
  { name: 'סלט תפו"א עם מיונז דל קלוריות', calories: 250, protein: 4, fat: 10, carbs: 36, portion: 'צלחת', category: 'סלטים', emoji: '🥔' },
  { name: 'סלט טונה עם מיונז רגיל', calories: 350, protein: 24, fat: 22, carbs: 10, portion: 'צלחת', category: 'סלטים', emoji: '🐟' },
  { name: 'סלט טונה עם מיונז דל קלוריות', calories: 240, protein: 24, fat: 10, carbs: 10, portion: 'צלחת', category: 'סלטים', emoji: '🐟' },
  { name: 'סלט אבוקדו וביצה', calories: 280, protein: 10, fat: 22, carbs: 10, portion: 'צלחת', category: 'סלטים', emoji: '🥑' },
  { name: 'סלט בולגרי', calories: 150, protein: 5, fat: 10, carbs: 10, portion: 'צלחת', category: 'סלטים', emoji: '🥗' },
  { name: 'מיונז רגיל', calories: 95, protein: 0, fat: 10, carbs: 1, portion: 'כף', category: 'תוספות', emoji: '🥫' },
  { name: 'מיונז דל קלוריות', calories: 35, protein: 0, fat: 3, carbs: 2, portion: 'כף', category: 'תוספות', emoji: '🥫' },

  // מעדנים
  { name: 'עוגת שוקולד', calories: 350, protein: 5, fat: 17, carbs: 45, portion: 'פרוסה', category: 'מעדנים', emoji: '🍰' },
  { name: 'עוגת גבינה', calories: 320, protein: 6, fat: 20, carbs: 28, portion: 'פרוסה', category: 'מעדנים', emoji: '🍰' },
  { name: 'עוגת גזר', calories: 300, protein: 4, fat: 15, carbs: 40, portion: 'פרוסה', category: 'מעדנים', emoji: '🍰' },
  { name: 'עוגת תפוחים', calories: 280, protein: 3, fat: 12, carbs: 42, portion: 'פרוסה', category: 'מעדנים', emoji: '🍰' },
  { name: 'טירמיסו', calories: 370, protein: 5, fat: 20, carbs: 42, portion: 'מנה', category: 'מעדנים', emoji: '🍰' },
  { name: 'פנה קוטה', calories: 280, protein: 4, fat: 18, carbs: 25, portion: 'מנה', category: 'מעדנים', emoji: '🍮' },
  { name: 'קרם ברולה', calories: 300, protein: 4, fat: 20, carbs: 26, portion: 'מנה', category: 'מעדנים', emoji: '🍮' },
  { name: 'מוס שוקולד', calories: 320, protein: 5, fat: 20, carbs: 30, portion: 'מנה', category: 'מעדנים', emoji: '🍫' },
  { name: 'סופלה שוקולד', calories: 380, protein: 6, fat: 22, carbs: 38, portion: 'מנה', category: 'מעדנים', emoji: '🍫' },
  { name: 'פרופיטרול', calories: 340, protein: 5, fat: 18, carbs: 40, portion: '3 יחידות', category: 'מעדנים', emoji: '🍩' },
  { name: 'אקלר', calories: 260, protein: 4, fat: 14, carbs: 30, portion: 'יחידה', category: 'מעדנים', emoji: '🍩' },
  { name: 'מלבי', calories: 180, protein: 3, fat: 5, carbs: 32, portion: 'מנה', category: 'מעדנים', emoji: '🍮' },
  { name: 'סהלב', calories: 200, protein: 4, fat: 6, carbs: 34, portion: 'כוס', category: 'מעדנים', emoji: '☕' },
  { name: 'קרמבו', calories: 115, protein: 1, fat: 4, carbs: 19, portion: 'יחידה', category: 'מעדנים', emoji: '🍫' },
  { name: 'בקלאווה', calories: 330, protein: 5, fat: 18, carbs: 38, portion: '2 יחידות', category: 'מעדנים', emoji: '🍯' },
  { name: 'כנאפה', calories: 400, protein: 8, fat: 18, carbs: 52, portion: 'מנה', category: 'מעדנים', emoji: '🍯' },
  { name: 'גלידה וניל', calories: 210, protein: 3, fat: 11, carbs: 24, portion: 'כדור', category: 'מעדנים', emoji: '🍦' },
  { name: 'גלידה שוקולד', calories: 230, protein: 4, fat: 12, carbs: 26, portion: 'כדור', category: 'מעדנים', emoji: '🍦' },
  { name: 'גלידה פירות', calories: 150, protein: 1, fat: 4, carbs: 28, portion: 'כדור', category: 'מעדנים', emoji: '🍦' },
  { name: 'פודינג שוקולד', calories: 200, protein: 4, fat: 7, carbs: 30, portion: 'מנה', category: 'מעדנים', emoji: '🍮' },
  { name: 'פודינג וניל', calories: 180, protein: 4, fat: 6, carbs: 28, portion: 'מנה', category: 'מעדנים', emoji: '🍮' },
  { name: 'מאפין שוקולד', calories: 380, protein: 5, fat: 16, carbs: 55, portion: 'יחידה', category: 'מעדנים', emoji: '🧁' },
  { name: 'מאפין אוכמניות', calories: 340, protein: 4, fat: 14, carbs: 50, portion: 'יחידה', category: 'מעדנים', emoji: '🧁' },
  { name: 'דונאט', calories: 300, protein: 4, fat: 16, carbs: 35, portion: 'יחידה', category: 'מעדנים', emoji: '🍩' },
  { name: 'דונאט במילוי', calories: 350, protein: 4, fat: 18, carbs: 42, portion: 'יחידה', category: 'מעדנים', emoji: '🍩' },
  { name: 'סופגנייה', calories: 400, protein: 5, fat: 20, carbs: 50, portion: 'יחידה', category: 'מעדנים', emoji: '🍩' },
  { name: 'קינוח פירות', calories: 120, protein: 1, fat: 0, carbs: 30, portion: 'מנה', category: 'מעדנים', emoji: '🍓' },
  { name: 'פחזנייה', calories: 250, protein: 3, fat: 12, carbs: 33, portion: 'יחידה', category: 'מעדנים', emoji: '🥐' },
  { name: 'רולדין קרואסון שוקולד', calories: 380, protein: 5, fat: 20, carbs: 44, portion: 'יחידה', category: 'מעדנים', emoji: '🥐' },

  // שוקולדים
  { name: 'שוקולד מריר 70%', calories: 170, protein: 2, fat: 12, carbs: 13, portion: '30 גרם', category: 'שוקולדים', emoji: '🍫' },
  { name: 'שוקולד חלב', calories: 160, protein: 2, fat: 9, carbs: 17, portion: '30 גרם', category: 'שוקולדים', emoji: '🍫' },
  { name: 'שוקולד לבן', calories: 170, protein: 2, fat: 10, carbs: 18, portion: '30 גרם', category: 'שוקולדים', emoji: '🍫' },
  { name: 'פרה חלב', calories: 55, protein: 1, fat: 3, carbs: 6, portion: 'יחידה', category: 'שוקולדים', emoji: '🍫' },
  { name: 'פרה אגוזים', calories: 60, protein: 1, fat: 4, carbs: 6, portion: 'יחידה', category: 'שוקולדים', emoji: '🍫' },
  { name: 'קינדר בואנו', calories: 120, protein: 2, fat: 7, carbs: 12, portion: 'יחידה', category: 'שוקולדים', emoji: '🍫' },
  { name: 'קינדר ביצת הפתעה', calories: 110, protein: 2, fat: 7, carbs: 11, portion: 'יחידה', category: 'שוקולדים', emoji: '🥚' },
  { name: 'סניקרס', calories: 250, protein: 4, fat: 12, carbs: 33, portion: 'יחידה', category: 'שוקולדים', emoji: '🍫' },
  { name: 'מארס', calories: 230, protein: 2, fat: 9, carbs: 36, portion: 'יחידה', category: 'שוקולדים', emoji: '🍫' },
  { name: 'טוויקס', calories: 250, protein: 3, fat: 12, carbs: 33, portion: 'יחידה', category: 'שוקולדים', emoji: '🍫' },
  { name: 'קליק', calories: 90, protein: 1, fat: 5, carbs: 10, portion: 'יחידה', category: 'שוקולדים', emoji: '🍫' },
  { name: 'פסק זמן', calories: 220, protein: 3, fat: 11, carbs: 28, portion: 'יחידה', category: 'שוקולדים', emoji: '🍫' },
  { name: 'שוקו בלי', calories: 130, protein: 1, fat: 7, carbs: 16, portion: 'יחידה', category: 'שוקולדים', emoji: '🍫' },
  { name: 'כדורי שוקולד', calories: 80, protein: 1, fat: 5, carbs: 8, portion: '2 כדורים', category: 'שוקולדים', emoji: '🍫' },
  { name: 'נוטלה', calories: 100, protein: 1, fat: 6, carbs: 11, portion: 'כף', category: 'שוקולדים', emoji: '🍫' },
  { name: 'ממרח שוקולד', calories: 90, protein: 1, fat: 5, carbs: 10, portion: 'כף', category: 'שוקולדים', emoji: '🍫' },
  { name: 'שוקו חם', calories: 180, protein: 5, fat: 6, carbs: 27, portion: 'כוס', category: 'שוקולדים', emoji: '☕' },
  { name: 'שוקו קר', calories: 160, protein: 5, fat: 4, carbs: 26, portion: 'כוס', category: 'שוקולדים', emoji: '🥛' },
  { name: 'פרלינים', calories: 70, protein: 1, fat: 5, carbs: 6, portion: 'יחידה', category: 'שוקולדים', emoji: '🍫' },
  { name: 'טראפלס שוקולד', calories: 80, protein: 1, fat: 6, carbs: 6, portion: 'יחידה', category: 'שוקולדים', emoji: '🍫' },
  { name: 'וופל בלגי עם שוקולד', calories: 420, protein: 6, fat: 22, carbs: 50, portion: 'יחידה', category: 'שוקולדים', emoji: '🧇' },
  { name: 'פונדו שוקולד', calories: 300, protein: 4, fat: 18, carbs: 32, portion: 'מנה', category: 'שוקולדים', emoji: '🫕' },
  { name: 'שוקולד מריר 85%', calories: 180, protein: 3, fat: 14, carbs: 10, portion: '30 גרם', category: 'שוקולדים', emoji: '🍫' },
  { name: 'חטיף אנרגיה שוקולד', calories: 200, protein: 8, fat: 8, carbs: 25, portion: 'יחידה', category: 'שוקולדים', emoji: '🍫' },
];

export const foodCategories = [
  'הכל', 'ישראלי', 'חלבון', 'לחמים', 'ירקות', 'פירות', 'חלב', 'חטיפים', 'משקאות', 'מזון מהיר', 'תוספות', 'מרקים', 'ארוחת בוקר', 'מנות עיקריות', 'סלטים', 'מעדנים', 'שוקולדים',
];
